import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { ID, WORKFLOW, ENDPOINT, FREEZE_SHA, DIMENSIONS, digest, scan, approved, validateFreeze, loadFrozen, history, stats, validateGate, validatePair, verifyPrior, runOne, finalizeTrial } from '../scripts/run-causal-continuity.mjs';
const freezeBytes=await readFile(new URL('../eval/causal-continuity-requests.json',import.meta.url));
const freeze=validateFreeze(freezeBytes),trial={freeze,manifest:{protocol:ID,testOnly:true}};
const SHA='a'.repeat(40),KEY='PRIVATE_FAKE_TEST_KEY!+/=';
const env=n=>({NEXUS_CAUSAL_APPROVED:'true',NEXUS_OVERAGE_CONFIRMED_OFF:'true',GITHUB_ACTIONS:'true',GITHUB_RUN_ATTEMPT:'1',GITHUB_SHA:SHA,GITHUB_REPOSITORY:'logan-suu/NexusScribe',GITHUB_RUN_ID:String(100+n),NEXUS_CI_RUN_ID:'90',NEXUS_API_KEY:KEY,...(n>1?{NEXUS_PRIOR_RUN_ID:String(99+n)}:{})});
const runs=n=>Array.from({length:n},(_,i)=>({id:101+i,display_title:`${ID}/call-${i+1}`,run_attempt:1,head_sha:SHA,event:'workflow_dispatch',path:'.github/workflows/'+WORKFLOW,status:i===n-1?'in_progress':'completed',conclusion:i===n-1?null:'success'}));
const ci={id:90,path:'.github/workflows/ci.yml',head_sha:SHA,status:'completed',conclusion:'success'};
const text=n=>Array.from({length:5},(_,i)=>String.fromCodePoint(0x4e00+n+i).repeat(n===3||n===4?80:100)).join('\n\n');
const envelope=(content,extra={})=>JSON.stringify({choices:[{finish_reason:'stop',message:{content}}],usage:{prompt_tokens:100,completion_tokens:200,total_tokens:300},...extra});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function io(before=async()=>{}){const files={};return{async write(p,x){await before(p,x);assert.ok(!Object.hasOwn(files,p),'immutable '+p);files[p]=Buffer.isBuffer(x)?Buffer.from(x):Buffer.from(typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');},async files(){return Object.fromEntries(Object.entries(files).map(([p,b])=>[p,Buffer.from(b)]));}};}
function gate(n,t=text(n)){return{protocol:ID,locked:true,masked:true,fullCandidateRead:true,status:'pass',textSha256:digest(t),storyInputSha256:digest(freeze.requests[n-1].body.messages[1].content),reviewer:'Offline guard fixture; not a literary judgment',items:DIMENSIONS.map(id=>({id,status:'acceptable',explanation:'Mechanical guard fixture only.',evidence:[{start:0,end:1,quote:t.slice(0,1)}]}))};}
function pair(a,b){return{locked:true,masked:true,status:'pass',outputSha256:[digest(a),digest(b)],preferred:'neither',causalImprovement:'neither',explanation:'Offline gate-shape fixture only.',materialVoiceRegression:false,checklistPadding:false,evidence:[a,b].map(t=>({textSha256:digest(t),start:0,end:1,quote:t.slice(0,1)}))};}
async function call({n=1,files={},gates=null,fetchImpl,storage=io(),environment=env(n),historyRuns=runs(n),timeoutMs=1000}={}){let calls=0;const ledger=await runOne({n,env:environment,trial,runs:historyRuns,ci,priorFiles:files,gates,io:storage,sleep:async ms=>assert.equal(ms,11000),fetchImpl:async(url,opts)=>{calls++;assert.equal(url,ENDPOINT);assert.equal(opts.redirect,'error');assert.equal(digest(opts.body),freeze.requests[n-1].bodySha256);return fetchImpl?fetchImpl(url,opts):new Response(envelope(text(n)));},timeoutMs});return{ledger,files:await storage.files(),calls};}

test('unchanged six-body freeze has exact parity and hashes',()=>{assert.equal(digest(freezeBytes),FREEZE_SHA);assert.equal(freeze.requests.length,6);assert.throws(()=>validateFreeze(Buffer.concat([freezeBytes,Buffer.from(' ')])),/FREEZE_INVALID/);});
test('manifest exact inventory and hashes validate offline',async()=>{assert.equal((await loadFrozen()).manifest.protocol,ID);});
test('approval, first attempt, fixed repo and range fail closed',()=>{for(const patch of [{NEXUS_CAUSAL_APPROVED:'false'},{NEXUS_OVERAGE_CONFIRMED_OFF:'false'},{GITHUB_RUN_ATTEMPT:'2'},{GITHUB_REPOSITORY:'another/repo'},{GITHUB_ACTIONS:'false'}])assert.throws(()=>approved({...env(1),...patch},1));for(const n of [0,7,1.5])assert.throws(()=>approved(env(1),n));});
test('duplicate, skipped, foreign source and failed previous runs block',()=>{for(const rs of [[...runs(1),...runs(1)],[],[{...runs(1)[0],head_sha:'b'.repeat(40)}],[{...runs(1)[0],run_attempt:2}]])assert.throws(()=>history({env:env(1),n:1,runs:rs,ci}));assert.throws(()=>history({env:env(1),n:1,runs:runs(1),ci:{...ci,conclusion:'failure'}}),/CI_REQUIRED/);});
test('direct escaped nested and common encoded secrets are withheld',()=>{for(const key of [KEY,JSON.stringify(KEY),KEY.split('').map(c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0')).join(''),Buffer.from(KEY).toString('base64'),Buffer.from(KEY).toString('base64url'),Buffer.from(KEY).toString('hex'),encodeURIComponent(KEY)])assert.equal(scan(key,env(1)),false);assert.equal(scan('harmless synthetic prose',env(1)),true);});
test('required gate rejects all N/A, uncertainty, wrong input/output and invented quote',()=>{const g=gate(1);assert.ok(validateGate(g,text(1),g.storyInputSha256));for(const change of [x=>x.items.forEach(i=>i.status='not_applicable'),x=>x.items[0].status='needs_edit/uncertain',x=>x.masked=false,x=>x.textSha256='0'.repeat(64),x=>x.items[0].evidence[0].quote='invented']){const v=structuredClone(g);change(v);assert.equal(validateGate(v,text(1),g.storyInputSha256),false);}});
test('pairwise gate binds both outputs and rejects regression/padding/missing evidence',()=>{const a=text(1),b=text(2),p=pair(a,b);assert.ok(validatePair(p,a,b));for(const patch of [{materialVoiceRegression:true},{checklistPadding:true},{locked:false},{evidence:[]},{causalImprovement:'unknown'},{outputSha256:['wrong','wrong']}])assert.equal(validatePair({...p,...patch},a,b),false);});
test('one successful request reserves first then retains exact final prose and missing usage honestly',async()=>{const result=await call({fetchImpl:async()=>new Response(envelope(text(1),{usage:{}}))});assert.equal(result.calls,1);assert.equal(result.ledger.status,'awaiting_masked_read');assert.equal(Buffer.from(result.files['raw-prose-01.bin']).toString(),text(1));assert.equal(result.ledger.usage.totalTokens.knownSum,null);assert.equal(result.ledger.usage.totalTokens.missingCalls,1);assert.ok(result.files['dispatch-01.json']);assert.equal(result.files['raw-01.bin'],undefined);});
for(const [label,body,expected,status]of [
 ['length failure',envelope('短文'),'DELIVERY_FAILED',200],
 ['truncation',envelope(text(1),{choices:[{finish_reason:'length',message:{content:text(1)}}]}),'OUTPUT_TRUNCATED',200],
 ['error status',envelope(text(1)),'UPSTREAM_ERROR',429],
 ['200 error object',envelope(text(1),{error:{message:'safe'}}),'RESPONSE_INVALID',200],
 ['malformed envelope','{bad','RESPONSE_INVALID',200],
 ['reasoning field',envelope(text(1),{choices:[{finish_reason:'stop',message:{content:text(1),reasoning_content:'DO NOT RETAIN HIDDEN'}}]}),'HIDDEN_REASONING',200],
 ['reasoning tokens',envelope(text(1),{usage:{completion_tokens_details:{reasoning_tokens:5}}}),'HIDDEN_REASONING',200],
 ['over budget',envelope(text(1),{usage:{completion_tokens:3001}}),'RESPONSE_INVALID',200],
 ['credential echo',envelope(KEY),'SECRET_ECHO',200],
 ['malformed tool calls',envelope(text(1),{choices:[{finish_reason:'stop',message:{content:text(1),tool_calls:{}}}]}),'RESPONSE_INVALID',200],
 ['legacy function call',envelope(text(1),{choices:[{finish_reason:'stop',message:{content:text(1),function_call:{name:'unknown',arguments:'{}'}}}]}),'RESPONSE_INVALID',200],
 ['wrong message role',envelope(text(1),{choices:[{finish_reason:'stop',message:{content:text(1),role:'tool'}}]}),'RESPONSE_INVALID',200],
 ['refusal',envelope(text(1),{choices:[{finish_reason:'stop',message:{content:text(1),refusal:'no'}}]}),'REFUSAL',200],
 ['content hidden reasoning',envelope('<think>DO NOT RETAIN HIDDEN</think>'+text(1)),'HIDDEN_REASONING',200],
 ['json array',envelope('['+text(1)+']'),'RESPONSE_INVALID',200],
 ['tilde fence',envelope('~~~\n'+text(1)+'\n~~~'),'RESPONSE_INVALID',200],
])test(label+' stops after one attempt',async()=>{const r=await call({fetchImpl:async()=>new Response(body,{status})});assert.equal(r.calls,1);assert.equal(r.ledger.attempts,1);assert.equal(r.ledger.status,'stopped');assert.equal(r.ledger.stages[0].error,expected);assert.ok(!JSON.stringify(r.files).includes('DO NOT RETAIN HIDDEN'));if(expected==='SECRET_ECHO'||expected==='HIDDEN_REASONING')assert.equal(r.files['raw-prose-01.bin'],undefined);});
test('network failure does not retry and records unknown usage',async()=>{const r=await call({fetchImpl:async()=>{throw Error(KEY);}});assert.equal(r.calls,1);assert.equal(r.ledger.stages[0].error,'UPSTREAM_ERROR');assert.equal(r.ledger.usage.totalTokens.knownSum,null);});
test('oversize stream stops and no raw envelope is retained',async()=>{const r=await call({fetchImpl:async()=>new Response('x'.repeat(128*1024+1))});assert.equal(r.ledger.stages[0].error,'RESPONSE_TOO_LARGE');assert.equal(r.files['raw-prose-01.bin'],undefined);});
test('timeout cannot persist late output after terminal inventory',async()=>{const storage=io(async p=>{if(p==='response-meta-01.json')await sleep(30);});const r=await call({storage,timeoutMs:5});assert.equal(r.ledger.status,'stopped');await sleep(50);const f=await storage.files(),index=JSON.parse(Buffer.from(f['index-01.json']).toString());assert.deepEqual(Object.keys(f).sort(),[...Object.keys(index.sha256),'index-01.json'].sort());assert.equal(f['completed-01.json'],undefined);assert.equal(f['raw-prose-01.bin'],undefined);});
test('timeout with transport ignoring abort has no late evidence writes',async()=>{const storage=io();const r=await call({storage,timeoutMs:5,fetchImpl:async()=>{await sleep(40);return new Response(envelope(text(1)));}});assert.equal(r.ledger.stages[0].error,'UPSTREAM_TIMEOUT');await sleep(60);assert.equal((await storage.files())['raw-prose-01.bin'],undefined);});
test('failed intent or reservation prevents provider dispatch',async()=>{for(const blocked of ['intent-01.json','dispatch-01.json']){let calls=0;const storage=io(async p=>{if(p===blocked)throw Error('disk');});try{await call({storage,fetchImpl:async()=>{calls++;return new Response(envelope(text(1)));}});}catch{}assert.equal(calls,0);}});
test('baseline delivery failure cannot be bypassed by next arm',async()=>{const first=await call({fetchImpl:async()=>new Response(envelope('短'))});await assert.rejects(call({n:2,files:first.files,gates:{individual:gate(1,'短')}}),/PRIOR_INVALID/);});
test('exact cumulative six-stage fake path and final masked gates are required',async()=>{let files={};for(let n=1;n<=6;n++){const gates=n===1?null:{individual:gate(n-1),...((n-1)%2===0?{pairwise:pair(text(n-2),text(n-1))}:{})};const r=await call({n,files,gates});assert.equal(r.calls,1);assert.equal(r.ledger.attempts,n);files=r.files;}const gates={individual:gate(6),pairwise:pair(text(5),text(6))};assert.equal(finalizeTrial({files,env:{...env(6),NEXUS_PRIOR_RUN_ID:'106'},trial,gates}).attempts,6);assert.throws(()=>finalizeTrial({files,env:{...env(6),NEXUS_PRIOR_RUN_ID:'106'},trial,gates:null}),/GATE_FAILED/);});
test('altered or missing prior evidence and failed masked gate prevent continuation',async()=>{const first=await call();for(const f of [{...first.files,'extra.json':Buffer.from('{}')},{...first.files,'completed-01.json':Buffer.from('{}')}])assert.throws(()=>verifyPrior(f,2,env(2),trial,{individual:gate(1)}),/PRIOR_INVALID/);const g=gate(1);g.items[0].status='clear_failure';await assert.rejects(call({n:2,files:first.files,gates:{individual:g}}),/GATE_FAILED/);});
