import test from 'node:test';
import assert from 'node:assert/strict';
import {createInitialState,saveRevision,proposePatch,validatePatch,commitPatch,undoCommit,generateDraft,reviewDraft,acceptDraft,rejectDraft,getContext,getImpacts,evaluateSupport,editDraft,createProjectFromConfig,proposeCustomPatch,stageProviderDraft,attachSemanticReview,createReviewBinding,getMemoryReviewGate,decideMemoryCandidate,hash,NEVER_MET,HAS_MET,PHONE,PAPER} from '../src/domain/engine.js';

// Legacy fixture acceptance is now an explicit per-candidate author decision.
function selectOriginalMemories(state) {let s=state;for(const row of getMemoryReviewGate(s,s.drafts[0].id)){if(!row.resolved)s=decideMemoryCandidate(s,s.drafts[0].id,{candidateId:row.candidateId,action:row.canKeep?'keep':'override_keep',reason:'测试作者逐条核对后保留原始候选',reviewHash:row.reviewHash},row.binding);}return s;}
const initial=()=>createInitialState();
const edit=(s,id,fn)=>{const c=s.chapters.find(c=>c.id===id);return saveRevision(s,id,fn(c.text),c.revision);};
const changed=()=>edit(initial(),'ch2',t=>t.replace(NEVER_MET,HAS_MET));
const committed=()=>{const s=changed();return commitPatch(s,proposePatch(s,'ch2'));};
const generated=()=>generateDraft(committed());
const reviewed=()=>{const s=generated();return reviewDraft(s,s.drafts.at(-1).id);};

test('seed is serializable and three accepted chapters have revision evidence',()=>{const s=initial();assert.deepEqual(JSON.parse(JSON.stringify(s)),s);assert.equal(s.chapters.length,3);assert.equal(s.chapters[1].revisions[0].paragraphs[1].text,NEVER_MET);});
test('save text independently of canon and retain previous revision',()=>{const s=changed();assert.equal(s.version,1);assert.equal(s.facts[0].value,'never_met');assert.equal(s.chapters[1].revision,2);assert.equal(s.chapters[1].revisions[0].text.includes(NEVER_MET),true);assert.equal(s.chapters[1].syncStatus,'PENDING');});
test('immutable save does not mutate original',()=>{const s=initial(),saved=JSON.stringify(s);edit(s,'ch2',t=>t.replace(NEVER_MET,HAS_MET));assert.equal(JSON.stringify(s),saved);});
test('stale text save is rejected',()=>assert.throws(()=>saveRevision(initial(),'ch2','different',0),{code:'STALE_REVISION'}));
test('empty text save rejected and identical text is idempotent',()=>{const s=initial();assert.throws(()=>saveRevision(s,'ch2','',1),{code:'INVALID_TEXT'});assert.deepEqual(saveRevision(s,'ch2',s.chapters[1].text,1),s);});
test('relation edit has narrowly scoped source-backed operation',()=>{const s=changed(),p=proposePatch(s,'ch2');assert.deepEqual(p.intents,['canon_update','event_update']);assert.equal(p.operations.length,1);assert.equal(p.operations[0].source.quote,HAS_MET);assert.equal(p.operations[0].source.revision,2);assert.equal(p.operations[0].source.paragraphId,'p2');assert.equal(validatePatch(s,p).valid,true);});
test('commit replaces world truth but preserves police ignorance',()=>{const s=committed();assert.equal(s.version,2);assert.equal(s.facts[0].value,'has_met');assert.equal(s.knowledge[0].status,'explicitly_unaware');assert.equal(s.factHistory[0].value,'never_met');assert.equal(s.factHistory[0].status,'superseded');assert.equal(s.events.length,1);});
test('only genuine stranger dependency invalidated',()=>{const impacts=getImpacts(committed());assert.equal(impacts.find(x=>x.id==='stranger').status,'invalid');assert.equal(impacts.find(x=>x.id==='police-reveal').status,'valid');assert.equal(impacts.find(x=>x.id==='storm').status,'valid');});
test('preview calculates same impacts without mutation',()=>{const s=changed(),before=JSON.stringify(s);const result=validatePatch(s,proposePatch(s,'ch2'));assert.equal(result.impacts[0].status,'invalid');assert.equal(JSON.stringify(s),before);});
test('pure prose creates no canon or preference changes',()=>{let s=edit(initial(),'ch2',t=>t.replace('缓缓走向窗前','走到窗前'));const p=proposePatch(s,'ch2');assert.deepEqual(p.intents,['local_prose']);assert.equal(p.operations.length,0);s=commitPatch(s,p);assert.deepEqual(s.facts,initial().facts);assert.deepEqual(s.preferences,[]);});
test('quoted or unsupported semantic edit remains pending and blocks promotion',()=>{const s=edit(initial(),'ch2',t=>t.replace(NEVER_MET,'陈默说：“我好像见过死者。”'));const p=proposePatch(s,'ch2');assert.equal(p.status,'blocked');assert.throws(()=>commitPatch(s,p),{code:'INVALID_PATCH'});assert.equal(s.facts[0].value,'never_met');});
test('mixed known canon plus unsupported additional claim blocks atomic patch',()=>{const s=edit(changed(),'ch2',t=>t+'\n警方已经知道一切。');assert.equal(proposePatch(s,'ch2').status,'blocked');});
test('cross-project patch rejected',()=>{const s=changed(),p=proposePatch(s,'ch2');p.projectId='other-project';assert.equal(validatePatch(s,p).valid,false);assert.throws(()=>commitPatch(s,p),{code:'INVALID_PATCH'});});
test('stale state patch rejected',()=>{const s=changed(),p=proposePatch(s,'ch2');s.version++;assert.equal(validatePatch(s,p).valid,false);});
test('stale text patch rejected',()=>{const s=changed(),p=proposePatch(s,'ch2'),next=edit(s,'ch2',t=>t.replace('缓缓走向窗前','走到窗前'));assert.equal(validatePatch(next,p).valid,false);});
test('tampering unsupported operation is rejected',()=>{const s=changed(),p=proposePatch(s,'ch2');p.operations[0].value='police_knows';assert.equal(validatePatch(s,p).valid,false);});
test('same commit is idempotent and conflicting reuse rejected',()=>{const s=changed(),p=proposePatch(s,'ch2'),next=commitPatch(s,p);assert.deepEqual(commitPatch(next,p),next);p.summary='different';assert.throws(()=>commitPatch(next,p),{code:'IDEMPOTENCY_CONFLICT'});});
test('removing telephone keeps paper OR support and future action valid',()=>{let s=edit(initial(),'ch1',t=>t.replace(PHONE+'\n',''));const p=proposePatch(s,'ch1');assert.equal(p.status,'proposed');s=commitPatch(s,p);assert.equal(s.evidence[0].active,false);assert.equal(s.knowledge[1].status,'knows');assert.deepEqual(evaluateSupport(s).sourceIds,['paper']);assert.equal(getImpacts(s).find(p=>p.id==='visit').status,'valid');});
test('future-only alternative support is unsupported, never false',()=>{const s=initial();s.evidence[0].active=false;s.evidence[1].storyTime=10;const result=evaluateSupport(s);assert.equal(result.status,'unsupported');assert.deepEqual(result.validPaths,[]);});
test('no alternatives produce unsupported knowledge and review-needed action',()=>{let s=edit(initial(),'ch1',t=>t.replace(PHONE+'\n',''));s=commitPatch(s,proposePatch(s,'ch1'));s=edit(s,'ch1',t=>t.replace(PAPER+'\n',''));s=commitPatch(s,proposePatch(s,'ch1'));assert.equal(s.knowledge[1].status,'unsupported');assert.equal(getImpacts(s).find(p=>p.id==='visit').status,'needs_review');});
test('AND support requires all active evidence',()=>{const s=initial();s.knowledge[1].supportSets=[['phone','paper']];s.evidence[0].active=false;assert.equal(evaluateSupport(s).status,'unsupported');});
test('context includes exact current original evidence and no superseded truth',()=>{const s=committed(),c=getContext(s);assert.equal(c.facts.length,1);assert.equal(c.facts[0].value,'has_met');assert.equal(c.sources[1].revision,2);assert.equal(c.sources[1].text.includes(HAS_MET),true);assert.deepEqual(c.staging,[]);});
test('outdated summaries cannot re-enter context',()=>{const s=committed();s.derived=[{chapterId:'ch2',revision:1,status:'valid',text:'outdated'},{chapterId:'ch2',revision:2,status:'valid',text:'current'}];assert.deepEqual(getContext(s).summaries.map(x=>x.text),['current']);});
test('pending semantic sync blocks generation',()=>assert.throws(()=>generateDraft(changed()),{code:'UNSYNCED_TEXT'}));
test('generated draft inherits relation without police leak and isolated key',()=>{const s=generated(),d=s.drafts.at(-1);assert.equal(d.text.includes('三年前的那次见面'),true);assert.equal(d.text.includes('警方继续核对'),true);assert.equal(d.staging.length,1);assert.equal(s.events.some(x=>x.label.includes('钥匙')),false);});
test('parallel drafts have independent run IDs and staging',()=>{let s=generated();s=generateDraft(s);assert.notEqual(s.drafts[0].runId,s.drafts[1].runId);assert.notEqual(s.drafts[0].staging[0].id,s.drafts[1].staging[0].id);const r=rejectDraft(s,s.drafts[0].id);assert.equal(r.drafts[1].staging.length,1);});
test('reject draft has no canon pollution',()=>{const s=generated(),before=JSON.stringify({facts:s.facts,events:s.events});const r=rejectDraft(s,s.drafts[0].id);assert.equal(r.drafts[0].status,'REJECTED');assert.deepEqual(r.drafts[0].staging,[]);assert.equal(JSON.stringify({facts:r.facts,events:r.events}),before);});
test('review checks key acquisition removed by final edit',()=>{let s=generated(),id=s.drafts[0].id;s=editDraft(s,id,s.drafts[0].text.replace('林夏从门框上方取下一把铜钥匙。',''));s=reviewDraft(s,id);assert.equal(s.drafts[0].review.passed,false);assert.equal(s.drafts[0].review.issues.some(i=>i.ruleId==='KEY_SUPPORT'),true);assert.throws(()=>acceptDraft(s,id),{code:'REVIEW_REQUIRED'});});
test('accept requires review and binds exact draft text',()=>{const s=generated(),id=s.drafts[0].id;assert.throws(()=>acceptDraft(s,id),{code:'REVIEW_REQUIRED'});const r=reviewDraft(s,id);r.drafts[0].text+='追加';assert.throws(()=>acceptDraft(r,id),{code:'REVIEW_REQUIRED'});});
test('review cannot approve stale source revision or stale canon',()=>{let s=reviewed(),id=s.drafts[0].id;s=edit(s,'ch2',t=>t.replace('缓缓走向窗前','走到窗前'));assert.throws(()=>acceptDraft(s,id),{code:'REVIEW_REQUIRED'});s=commitPatch(s,proposePatch(s,'ch2'));s=reviewDraft(s,id);assert.equal(s.drafts[0].review.passed,false);});
test('accepted final draft atomically promotes key and text with idempotence',()=>{let s=reviewed(),id=s.drafts[0].id;s=acceptDraft(selectOriginalMemories(s),id);assert.equal(s.drafts[0].status,'ACCEPTED');assert.equal(s.events.filter(e=>e.label.includes('钥匙')).length,1);assert.equal(s.chapters[2].text,s.drafts[0].text);assert.deepEqual(acceptDraft(s,id),s);});
test('rejected draft cannot be accepted',()=>{let s=reviewed(),id=s.drafts[0].id;s=rejectDraft(s,id);assert.throws(()=>acceptDraft(s,id),{code:'DRAFT_STATUS'});});
test('undo creates compensation preserving commits, old text and history',()=>{const s=committed(),r=undoCommit(s,s.commits[0].id);assert.equal(r.version,3);assert.equal(r.facts[0].value,'never_met');assert.equal(r.commits.length,2);assert.equal(r.commits[1].kind,'compensation');assert.equal(r.chapters[1].text.includes(HAS_MET),true);assert.equal(r.chapters[1].syncStatus,'NEEDS_REVIEW');assert.equal(r.factHistory.length,1);assert.deepEqual(undoCommit(r,s.commits[0].id),r);});
test('undo refuses dependent accepted draft and preserves state',()=>{let s=reviewed();s=acceptDraft(selectOriginalMemories(s),s.drafts[0].id);const before=JSON.stringify(s);assert.throws(()=>undoCommit(s,s.commits[0].id),{code:'DEPENDENT_COMMIT'});assert.equal(JSON.stringify(s),before);});
test('full state restores JSON including revisions staging reviews and audit log',()=>{const s=reviewed(),restored=JSON.parse(JSON.stringify(s));assert.deepEqual(restored,s);assert.equal(acceptDraft(selectOriginalMemories(restored),restored.drafts[0].id).version,3);});

test('multiple autosaves retain original unsynchronized semantic change',()=>{let s=changed();s=edit(s,'ch2',t=>t.replace('缓缓走向窗前','走到窗前'));const p=proposePatch(s,'ch2');assert.equal(p.operations[0].op,'set_relationship');assert.equal(commitPatch(s,p).facts[0].value,'has_met');});
test('deleting both support sources in one edit yields unsupported not false',()=>{let s=edit(initial(),'ch1',t=>t.replace(PHONE+'\n','').replace(PAPER+'\n',''));const p=proposePatch(s,'ch1');assert.equal(p.status,'proposed');s=commitPatch(s,p);assert.equal(s.knowledge[1].status,'unsupported');});
test('undo can be reconciled with retained edited text through new patch',()=>{let s=committed();s=undoCommit(s,s.commits[0].id);const p=proposePatch(s,'ch2');assert.equal(p.operations.length,1);s=commitPatch(s,p);assert.equal(s.facts[0].value,'has_met');assert.equal(s.chapters[1].syncStatus,'CLEAN');});
test('editing away staging evidence blocks acceptance instead of silently dropping the event',()=>{let s=generated(),id=s.drafts[0].id;s=editDraft(s,id,s.drafts[0].text.replace('林夏从门框上方取下一把铜钥匙。','').replace('她用铜钥匙打开仓库的门，潮湿的纸张气味迎面涌来。','她没有进门。'));s=reviewDraft(s,id);assert.equal(s.drafts[0].review.passed,false);assert.ok(s.drafts[0].review.issues.some(i=>i.ruleId==='STAGING_EVIDENCE'));assert.throws(()=>acceptDraft(s,id),{code:'REVIEW_REQUIRED'});assert.equal(s.events.some(e=>e.label.includes('钥匙')),false);});
test('custom project starts free of demonstration canon and exposes supplied premise',()=>{const s=createProjectFromConfig({projectId:'custom-1',title:'海边书店',premise:'一位书店老板追寻失踪手稿',protagonist:'阿岚'});assert.equal(s.projectId,'custom-1');assert.equal(s.title,'海边书店');assert.deepEqual(s.facts,[]);assert.deepEqual(s.knowledge,[]);assert.deepEqual(s.plans,[]);assert.equal(s.chapters[0].text.includes('书店老板'),true);assert.equal(getContext(s).pov,'阿岚');assert.equal(JSON.stringify(s).includes('陈默'),false);});
test('custom semantic edits remain pending and require a real provider',()=>{let s=createProjectFromConfig({title:'故事'});s=edit(s,'ch1',t=>t+'主角发现了秘密。');assert.equal(proposePatch(s,'ch1').status,'blocked');assert.throws(()=>generateDraft(s),{code:'PROVIDER_REQUIRED'});});
test('separate project IDs cannot exchange supported demo patches',()=>{const a=changed(),p=proposePatch(a,'ch2');const b=createInitialState('another-project');assert.equal(validatePatch(b,p).valid,false);});

const custom=()=>createProjectFromConfig({projectId:'custom-test',title:'书店谜案',premise:'阿岚寻找手稿',outline:['发现手稿','追查来历']});
const providerResult=(s)=>({text:'阿岚拿起一封信。警方已经知道真相。',provider:'mock-provider',context:getContext(s),staging:[{label:'阿岚获得信件',sourceQuote:'阿岚拿起一封信。'}]});
test('custom author classification syncs local prose without adding canon',()=>{let s=edit(custom(),'ch1',t=>t+'阿岚走进书店。');const p=proposeCustomPatch(s,'ch1',{intent:'local_prose'});s=commitPatch(s,p);assert.deepEqual(s.facts,[]);assert.equal(s.chapters[0].syncedRevision,2);assert.equal(s.chapters[0].syncStatus,'CLEAN');});
test('custom author fact is explicitly grounded and authority labeled',()=>{let s=edit(custom(),'ch1',t=>t+'阿岚从小住在海边。');const p=proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'阿岚从小住在海边。'});s=commitPatch(s,p);assert.equal(s.facts[0].label,'阿岚从小住在海边。');assert.equal(s.facts[0].authority,'explicit_author_decision');assert.equal(s.facts[0].source.revision,2);assert.equal(s.knowledge.length,0);assert.deepEqual(commitPatch(s,p),s);});
test('custom fact cannot promote absent statement or invented provider intent',()=>{const s=custom();assert.throws(()=>proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'不存在的事实'}),{code:'AUTHOR_EVIDENCE'});assert.throws(()=>proposeCustomPatch(s,'ch1',{intent:'model_inferred'}),{code:'AUTHOR_INSTRUCTION'});});
test('custom author patch rejects tampering and stale text',()=>{const s=edit(custom(),'ch1',t=>t+'阿岚回家。'),p=proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'阿岚回家。'});const changed=structuredClone(p);changed.operations[0].statement='阿岚出国。';assert.equal(validatePatch(s,changed).valid,false);const next=edit(s,'ch1',t=>t+'下雨了。');assert.equal(validatePatch(next,p).valid,false);});
test('custom outline remains author-provided ready plan without fake analysis',()=>{const s=custom(),p=getImpacts(s);assert.equal(p[0].status,'ready');assert.equal(p[0].title,'发现手稿');assert.equal(p[0].reason.includes('尚未'),true);});
test('provider staging creates isolated candidate without canon side effect',()=>{const s=custom(),before=JSON.stringify(s),n=stageProviderDraft(s,providerResult(s),'ch1');assert.equal(JSON.stringify(s),before);assert.equal(n.drafts[0].chapterId,'ch1');assert.equal(n.events.length,0);assert.equal(n.facts.length,0);assert.equal(n.drafts[0].staging[0].status,'proposed');});
test('provider result rejects missing or different project context',()=>{const s=custom(),r=providerResult(s);delete r.context;assert.throws(()=>stageProviderDraft(s,r,'ch1'),{code:'PROJECT_MISMATCH'});r.context={...getContext(s),projectId:'elsewhere'};assert.throws(()=>stageProviderDraft(s,r,'ch1'),{code:'PROJECT_MISMATCH'});});
test('provider result rejects old state and text snapshots',()=>{const s=custom(),r=providerResult(s);r.context.version=0;assert.throws(()=>stageProviderDraft(s,r,'ch1'),{code:'STALE_STATE'});r.context=getContext(s);r.context.sources[0].revision=0;assert.throws(()=>stageProviderDraft(s,r,'ch1'),{code:'STALE_REVISION'});});
test('provider staging blocks unsynced text and unsupported candidate evidence',()=>{const s=custom(),r=providerResult(s),pending=edit(s,'ch1',t=>t+'改文');assert.throws(()=>stageProviderDraft(pending,r,'ch1'),{code:'UNSYNCED_TEXT'});r.staging[0].sourceQuote='另一本书';assert.throws(()=>stageProviderDraft(s,r,'ch1'),{code:'INVALID_STAGING'});});
test('custom review does not apply demo character knowledge constraints',()=>{let s=custom();s=stageProviderDraft(s,providerResult(s),'ch1');s=reviewDraft(s,s.drafts[0].id);assert.equal(s.drafts[0].review.passed,true);assert.equal(s.drafts[0].review.semanticStatus,'not_evaluated');assert.equal(s.drafts[0].review.limitations.length,1);});
test('custom acceptance writes targeted chapter only and promotes supported event',()=>{let s=custom(),third=s.chapters[2].text;s=stageProviderDraft(s,providerResult(s),'ch1');s=reviewDraft(s,s.drafts[0].id);s=acceptDraft(selectOriginalMemories(s),s.drafts[0].id);assert.equal(s.chapters[0].text,'阿岚拿起一封信。警方已经知道真相。');assert.equal(s.chapters[2].text,third);assert.equal(s.events[0].label,'阿岚获得信件');assert.equal(s.facts.length,0);});
test('custom rejected candidate cannot pollute another draft or world events',()=>{let s=custom();s=stageProviderDraft(s,providerResult(s),'ch1');s=stageProviderDraft(s,providerResult(s),'ch2');s=rejectDraft(s,s.drafts[0].id);assert.equal(s.drafts[0].staging.length,0);assert.equal(s.drafts[1].staging.length,1);assert.equal(s.events.length,0);});
test('review binds target chapter and staging as well as text',()=>{let s=custom();s=stageProviderDraft(s,providerResult(s),'ch1');s=reviewDraft(s,s.drafts[0].id);const a=structuredClone(s);a.drafts[0].chapterId='ch2';assert.throws(()=>acceptDraft(a,a.drafts[0].id),{code:'REVIEW_REQUIRED'});const b=structuredClone(s);b.drafts[0].staging[0].label='别的事实';assert.throws(()=>acceptDraft(b,b.drafts[0].id),{code:'REVIEW_REQUIRED'});});

const liveDraft=()=>{const s=custom(),r=providerResult(s);r.provider={id:'live-test-provider',isLive:true};return stageProviderDraft(s,r,'ch1');};
const advisory=(issues=[])=>({summary:'模型候选审查结果',issues,checks:['角色知识候选检查'],provider:{id:'live-test-provider',isLive:true}});
const reviewExpected=s=>createReviewBinding(s,s.drafts[0].id);
test('live provider identity preserved and semantic review required before acceptance',()=>{let s=liveDraft();assert.equal(s.drafts[0].provider,'live-test-provider');assert.equal(s.drafts[0].requiresSemanticReview,true);s=reviewDraft(s,s.drafts[0].id);assert.throws(()=>acceptDraft(s,s.drafts[0].id),{code:'SEMANTIC_REVIEW_REQUIRED'});});
test('attach semantic advisory preserves canon and structural review as distinct',()=>{const s=liveDraft(),before=JSON.stringify(s),n=attachSemanticReview(s,s.drafts[0].id,advisory(),reviewExpected(s));assert.equal(JSON.stringify(s),before);assert.deepEqual(n.facts,s.facts);assert.deepEqual(n.events,s.events);assert.equal(n.drafts[0].review,null);assert.equal(n.drafts[0].modelReview.semanticStatus,'model_reviewed_unverified');assert.equal(n.drafts[0].modelReview.advisory,true);});
test('live advisory requires exact expected state revision and text hash',()=>{const s=liveDraft(),id=s.drafts[0].id,e=reviewExpected(s);assert.throws(()=>attachSemanticReview(s,id,advisory()),{code:'STALE_SEMANTIC_REVIEW'});for(const key of ['stateVersion','draftRevision','textHash']){const invalid={...e,[key]:key==='textHash'?'old':999};assert.throws(()=>attachSemanticReview(s,id,advisory(),invalid),{code:'STALE_SEMANTIC_REVIEW'});}});
test('semantic advisory rejects stale source chapter revision',()=>{let s=liveDraft(),expected=reviewExpected(s);s=edit(s,'ch1',t=>t+'变更');assert.throws(()=>attachSemanticReview(s,s.drafts[0].id,advisory(),expected),{code:'STALE_SEMANTIC_REVIEW'});});
test('live model errors block acceptance despite structural pass',()=>{let s=liveDraft(),id=s.drafts[0].id;s=attachSemanticReview(s,id,advisory([{severity:'error',explanation:'可能提前知情',sourceQuote:'警方已经知道真相。'}]),reviewExpected(s));s=reviewDraft(s,id);assert.equal(s.drafts[0].review.passed,true);assert.throws(()=>acceptDraft(s,id),{code:'SEMANTIC_REVIEW_ERRORS'});});
test('live model warnings remain visible and allow author acceptance',()=>{let s=liveDraft(),id=s.drafts[0].id;s=attachSemanticReview(s,id,advisory([{severity:'warning',explanation:'建议核实来源',sourceQuote:'警方已经知道真相。'}]),reviewExpected(s));s=reviewDraft(s,id);s=acceptDraft(selectOriginalMemories(s),id);assert.equal(s.drafts[0].status,'ACCEPTED');assert.equal(s.drafts[0].modelReview.issues[0].severity,'warning');assert.equal(s.drafts[0].modelReview.semanticStatus,'model_reviewed_unverified');});
test('editing draft clears structural and semantic reviews',()=>{let s=liveDraft(),id=s.drafts[0].id;s=attachSemanticReview(s,id,advisory(),reviewExpected(s));s=reviewDraft(s,id);s=editDraft(s,id,s.drafts[0].text+'灯灭了。');assert.equal(s.drafts[0].modelReview,null);assert.equal(s.drafts[0].review,null);s=reviewDraft(s,id);assert.throws(()=>acceptDraft(s,id),{code:'SEMANTIC_REVIEW_REQUIRED'});});
test('semantic issue schema forbids invented quotes unknown fields and severities',()=>{const s=liveDraft(),id=s.drafts[0].id;for(const issue of [{severity:'note',explanation:'说明',sourceQuote:'阿岚拿起一封信。'},{severity:'warning',explanation:'说明',sourceQuote:'没有这句原文'},{severity:'warning',explanation:'说明',sourceQuote:''},{severity:'warning',explanation:'说明',sourceQuote:'阿岚拿起一封信。',autoPromote:true}])assert.throws(()=>attachSemanticReview(s,id,advisory([issue]),reviewExpected(s)),{code:'INVALID_SEMANTIC_REVIEW'});});
test('state advance invalidates existing semantic advisory acceptance',()=>{let s=liveDraft(),id=s.drafts[0].id;s=attachSemanticReview(s,id,advisory(),reviewExpected(s));s=reviewDraft(s,id);s=commitPatch(s,proposeCustomPatch(s,'ch1',{intent:'local_prose'}));assert.throws(()=>acceptDraft(s,id),{code:'REVIEW_REQUIRED'});assert.throws(()=>attachSemanticReview(s,id,advisory(),reviewExpected(s)),{code:'STALE_SEMANTIC_REVIEW'});});

const customFact=()=>{let s=edit(custom(),'ch1',t=>t+'阿岚从小住在海边。');return commitPatch(s,proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'阿岚从小住在海边。'}));};
const replacement=()=>{let s=customFact();const id=s.facts[0].id;s=edit(s,'ch1',t=>t.replace('阿岚从小住在海边。','阿岚从小住在山里。'));return {s,id,p:proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'阿岚从小住在山里。',targetFactId:id})};};
test('explicit author replacement keeps stable ID and exactly one active version',()=>{const {s,id,p}=replacement(),n=commitPatch(s,p);assert.equal(p.operations[0].op,'supersede_author_fact');assert.equal(p.operations[0].expectedRecordVersion,1);assert.equal(n.facts.length,1);assert.equal(n.facts[0].id,id);assert.equal(n.facts[0].recordVersion,2);assert.equal(n.facts[0].value,'阿岚从小住在山里。');assert.equal(n.facts[0].source.revision,3);assert.equal(n.factHistory[0].value,'阿岚从小住在海边。');assert.equal(n.factHistory[0].status,'superseded');assert.equal(p.authorInstruction.targetFactId,id);});
test('author replacement refuses stale target record version even with same state version',()=>{const {s,p}=replacement();s.facts[0].recordVersion++;assert.equal(validatePatch(s,p).valid,false);assert.throws(()=>commitPatch(s,p),{code:'INVALID_PATCH'});});
test('compensation undo restores old author fact and retains replacement audit',()=>{const {s,id,p}=replacement(),n=commitPatch(s,p),restored=undoCommit(n,n.commits.at(-1).id);assert.equal(restored.facts.length,1);assert.equal(restored.facts[0].id,id);assert.equal(restored.facts[0].value,'阿岚从小住在海边。');assert.equal(restored.facts[0].recordVersion,1);assert.equal(restored.factHistory.length,1);assert.equal(restored.commits.at(-1).kind,'compensation');});
test('author replacement refuses missing unconfirmed foreign and demo targets',()=>{for(const mode of ['missing','unconfirmed','foreign','demo']){const {s,id}=replacement();let targetFactId=id;if(mode==='missing')targetFactId='missing';if(mode==='unconfirmed')s.facts[0].status='proposed';if(mode==='foreign')s.facts[0].projectId='foreign';if(mode==='demo'){s.facts.push({...initial().facts[0],projectId:s.projectId});targetFactId='relationship';}assert.throws(()=>proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'阿岚从小住在山里。',targetFactId}),{code:'AUTHOR_TARGET'});}});
test('append remains explicit default and never guesses equivalent target',()=>{const {s}=replacement(),p=proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:'阿岚从小住在山里。'});assert.equal(p.operations[0].op,'append_author_fact');assert.equal(p.authorInstruction.targetFactId,undefined);assert.equal(commitPatch(s,p).facts.length,2);});
test('local prose instruction cannot quietly target a confirmed fact',()=>{const {s,id}=replacement();assert.throws(()=>proposeCustomPatch(s,'ch1',{intent:'local_prose',targetFactId:id}),{code:'AUTHOR_TARGET'});});

const intentFields = {title:'  海边书店  ',idea:'手稿消失。\n只留下一封信。',protagonist:'阿岚，一位修复师',tone:'温暖而克制',pov:'第一人称',goal:'找到手稿的主人',boundaries:'不以失忆解谜；不要血腥描写'};
const contractKeys = {title:'title',idea:'premise',protagonist:'protagonist',tone:'emotionalDirection',pov:'pov',goal:'desire',boundaries:'boundaries'};
test('context carries all seven exact author inputs separately from Canon',()=>{const s=createProjectFromConfig(intentFields),c=getContext(s);assert.deepEqual(c.constitution,intentFields);assert.deepEqual(c.facts,[]);assert.deepEqual(c.knowledge,[]);assert.equal(c.pov,intentFields.protagonist);assert.deepEqual(c.forbiddenReveals,[]);assert.equal(c.constitution.pov,'第一人称');});
test('top-level author fields override conflicting contract properties and entries',()=>{const contract={status:'proposal',fields:Object.values(contractKeys).map(key=>({key,value:'旧值',status:'proposed',source:'model'}))};for(const key of Object.values(contractKeys))contract[key]='旧约定';const s=createProjectFromConfig({...intentFields,contract}),c=getContext(s);for(const [key,value] of Object.entries(intentFields))assert.equal(c.constitution[key],value);assert.deepEqual(c.constitution.contract,contract);});
test('missing top-level intent falls back to canonical contract aliases for all seven fields',()=>{const contract={};for(const [name,key] of Object.entries(contractKeys))contract[key]=intentFields[name];const c=getContext(createProjectFromConfig({contract}));for(const [key,value] of Object.entries(intentFields))assert.equal(c.constitution[key],value);});
test('missing canonical contract properties fall back to fields entries with exact strings',()=>{const contract={status:'proposal',fields:Object.entries(contractKeys).map(([name,key])=>({key,value:intentFields[name],status:'deferred',source:'model-proposal'}))};const c=getContext(createProjectFromConfig({contract}));for(const [key,value] of Object.entries(intentFields))assert.equal(c.constitution[key],value);assert.equal(c.constitution.contract.status,'proposal');assert.equal(c.constitution.contract.fields[0].status,'deferred');});
test('explicit empty top-level inputs clear all seven old contract values',()=>{const input={},contract={fields:[]};for(const [name,key] of Object.entries(contractKeys)){input[name]='';contract[key]=intentFields[name];contract.fields.push({key,value:intentFields[name],status:'confirmed',source:'old-user'});}const c=getContext(createProjectFromConfig({...input,contract}));for(const key of Object.keys(contractKeys))assert.equal(c.constitution[key],'');});
test('empty canonical contract value is retained rather than resurrected from fields',()=>{const contract={premise:'',emotionalDirection:'',desire:'',boundaries:'',fields:[{key:'premise',value:'旧灵感'},{key:'emotionalDirection',value:'旧情绪'},{key:'desire',value:'旧目标'},{key:'boundaries',value:'旧边界'}]};const c=getContext(createProjectFromConfig({contract}));for(const key of ['idea','tone','goal','boundaries'])assert.equal(c.constitution[key],'');});
test('constitution preserves full contract metadata without implicit confirmation or source mutation',()=>{const contract={status:'proposal',schemaVersion:3,unresolved:['身份待定'],provenance:{id:'model-a',isLive:true},fields:[{key:'boundaries',value:'待定',status:'deferred',source:'template',sourceRef:{revision:7}}],extra:{nested:['保留']}};const s=createProjectFromConfig({contract}),before=JSON.stringify(s),c=getContext(s);assert.deepEqual(c.constitution.contract,contract);assert.equal(JSON.stringify(s),before);c.constitution.contract.fields[0].status='confirmed';c.constitution.contract.extra.nested.push('变更');assert.equal(JSON.stringify(s),before);assert.deepEqual(s.facts,[]);});
test('constitution remains exact through JSON restore and project switching',()=>{const a=createProjectFromConfig({...intentFields,projectId:'intent-a',contract:{status:'proposal',fields:[]}}),b=createProjectFromConfig({projectId:'intent-b',title:'另一部小说',idea:'不同灵感',boundaries:''});const restored=JSON.parse(JSON.stringify(a));assert.deepEqual(getContext(restored).constitution,getContext(a).constitution);assert.equal(getContext(b).constitution.title,'另一部小说');assert.equal(getContext(b).constitution.boundaries,'');assert.equal(getContext(a).constitution.boundaries,intentFields.boundaries);assert.equal(getContext(b).constitution.tone,'');});
test('constitution does not alter legacy constraints viewpoint or demo context',()=>{const constraints=['不能泄露结局'];const s=createProjectFromConfig({...intentFields,constraints}),c=getContext(s);assert.deepEqual(c.forbiddenReveals,constraints);assert.equal(c.pov,intentFields.protagonist);assert.equal(c.constitution.boundaries,intentFields.boundaries);assert.equal(c.constitution.tone,intentFields.tone);assert.equal(Object.hasOwn(getContext(initial()),'constitution'),false);});

test('review binding captures complete immutable origin and context before async work',()=>{const s=liveDraft(),before=JSON.stringify(s),b=createReviewBinding(s,s.drafts[0].id);assert.deepEqual(Object.keys(b),['projectId','draftId','runId','chapterId','stateVersion','draftRevision','textHash','stagingHash','chapterRevisions','contextHash','textSnapshot','stagingSnapshot','contextSnapshot','memoryReviewEpoch']);assert.equal(b.projectId,s.projectId);assert.equal(b.runId,s.drafts[0].runId);assert.equal(b.contextHash,hash(JSON.stringify(getContext(s))));b.chapterRevisions.ch1=999;assert.equal(JSON.stringify(s),before);});
test('async project switch rejects old report despite identical draft ID text and revisions',()=>{const a=liveDraft(),binding=createReviewBinding(a,a.drafts[0].id);let b=createProjectFromConfig({...a.config,projectId:'different-project'});b=stageProviderDraft(b,{...providerResult(b),provider:{id:'live-test-provider',isLive:true}},'ch1');assert.equal(b.drafts[0].id,a.drafts[0].id);assert.equal(b.drafts[0].text,a.drafts[0].text);assert.equal(b.drafts[0].revision,a.drafts[0].revision);assert.equal(b.version,a.version);const before=JSON.stringify(b);assert.throws(()=>attachSemanticReview(b,b.drafts[0].id,advisory(),binding),{code:'STALE_SEMANTIC_REVIEW'});assert.equal(JSON.stringify(b),before);});
test('async same-project draft switch rejects review for identical candidate text',()=>{let s=liveDraft();const binding=createReviewBinding(s,s.drafts[0].id);s=stageProviderDraft(s,{...providerResult(s),provider:{id:'live-test-provider',isLive:true}},'ch1');assert.equal(s.drafts[0].text,s.drafts[1].text);assert.throws(()=>attachSemanticReview(s,s.drafts[1].id,advisory(),binding),{code:'STALE_SEMANTIC_REVIEW'});});
test('legacy or incomplete bindings require a new semantic review',()=>{const s=liveDraft(),id=s.drafts[0].id;const legacy={stateVersion:s.version,draftRevision:1,textHash:hash(s.drafts[0].text)};assert.throws(()=>attachSemanticReview(s,id,advisory(),legacy),{code:'STALE_SEMANTIC_REVIEW'});for(const key of ['projectId','draftId','runId','chapterId','contextHash','chapterRevisions']){const binding=createReviewBinding(s,id);delete binding[key];assert.throws(()=>attachSemanticReview(s,id,advisory(),binding),{code:'STALE_SEMANTIC_REVIEW'});}});
test('author constitution changes invalidate pending review without state version bump',()=>{let s=liveDraft(),id=s.drafts[0].id;const binding=createReviewBinding(s,id),version=s.version;s.config.boundaries='不得新增转述中间人';assert.equal(s.version,version);assert.throws(()=>attachSemanticReview(s,id,advisory(),binding),{code:'STALE_SEMANTIC_REVIEW'});});
test('acceptance invalidates attached model review after constitution-only change',()=>{let s=liveDraft(),id=s.drafts[0].id;s=attachSemanticReview(s,id,advisory(),createReviewBinding(s,id));s=reviewDraft(s,id);s.config.tone='新增作者情绪要求';assert.throws(()=>acceptDraft(s,id),{code:'SEMANTIC_REVIEW_REQUIRED'});});
test('acceptance rejects legacy missing or tampered stored review binding',()=>{let s=liveDraft(),id=s.drafts[0].id;s=attachSemanticReview(s,id,advisory(),createReviewBinding(s,id));s=reviewDraft(s,id);for(const key of ['missing','projectId','draftId','runId','contextHash','chapterRevisions']){const altered=structuredClone(s);if(key==='missing')delete altered.drafts[0].modelReview.binding;else if(key==='chapterRevisions')altered.drafts[0].modelReview.binding.chapterRevisions.ch1=888;else altered.drafts[0].modelReview.binding[key]='wrong-origin';assert.throws(()=>acceptDraft(altered,id),{code:'SEMANTIC_REVIEW_REQUIRED'});}});
test('unchanged JSON-restored complete binding remains valid through structural review and acceptance',()=>{let s=liveDraft(),id=s.drafts[0].id,expected=createReviewBinding(s,id);s=JSON.parse(JSON.stringify(s));s=attachSemanticReview(s,id,advisory(),JSON.parse(JSON.stringify(expected)));assert.equal(s.drafts[0].modelReview.binding.memoryReviewEpoch,expected.memoryReviewEpoch+1);assert.deepEqual(s.drafts[0].memoryBindingSnapshots.find(item=>item.id===s.drafts[0].modelReview.binding.snapshotId).values,{textSnapshot:expected.textSnapshot,stagingSnapshot:expected.stagingSnapshot,contextSnapshot:expected.contextSnapshot});s=reviewDraft(s,id);s=JSON.parse(JSON.stringify(s));assert.equal(acceptDraft(selectOriginalMemories(s),id).drafts[0].status,'ACCEPTED');});

test('paragraph anchors survive acceptance with revision-local source metadata',()=>{
 let s=custom();const text='阿岚到达码头。\n阿岚拿起一封信。';s=stageProviderDraft(s,{text,context:getContext(s),staging:[{label:'获得信件',sourceQuote:'阿岚拿起一封信。',sourceParagraphIndex:1}]},'ch1');const id=s.drafts[0].id;
 s=reviewDraft(s,id);s=acceptDraft(selectOriginalMemories(s),id);assert.equal(s.events[0].source.paragraphId,'p2');assert.equal(s.events[0].source.revision,s.chapters[0].revision);assert.equal(s.events[0].source.quote,s.chapters[0].revisions.at(-1).paragraphs[1].text);
});
test('incorrect anchor rejected and edited anchor drift blocks even if quote survives elsewhere',()=>{
 let s=custom();const text='阿岚到达码头。\n阿岚拿起一封信。';const result={text,context:getContext(s),staging:[{label:'获得信件',sourceQuote:'阿岚拿起一封信。',sourceParagraphIndex:0}]};
 assert.throws(()=>stageProviderDraft(s,result,'ch1'),{code:'INVALID_STAGING'});
 result.staging[0].sourceParagraphIndex=1;s=stageProviderDraft(s,result,'ch1');const id=s.drafts[0].id;s=editDraft(s,id,'新增段落。\n'+text);s=reviewDraft(s,id);assert.ok(s.drafts[0].review.issues.some(i=>i.ruleId==='STAGING_ANCHOR'));assert.throws(()=>acceptDraft(s,id),{code:'REVIEW_REQUIRED'});assert.equal(s.events.length,0);
});
