import test from 'node:test';
import assert from 'node:assert/strict';
import * as e from '../src/domain/engine.js';
const blue='小舟的纸灯是蓝色的。';
function fixture(text='小舟提着小红纸灯。',fact=blue){
 let s=e.createProjectFromConfig({projectId:'fact-test',idea:'纸灯故事',chapters:[{text:fact}]});
 s=e.commitPatch(s,e.proposeCustomPatch(s,'ch1',{intent:'author_fact',statement:fact}));
 s=e.stageProviderDraft(s,{text,staging:[],provider:{id:'test',isLive:true},context:e.getContext(s)},'ch2');
 return e.reviewDraft(s,s.drafts[0].id);
}
function report(s,status='contradiction',quote=s.drafts[0].text){return {summary:'测试模型判断，非语义正确性证明',issues:[{severity:'warning',explanation:'节奏可再润色',sourceQuote:s.drafts[0].text}],checks:['设定'],provider:'test',factChecks:[{factId:s.facts[0].id,recordVersion:s.facts[0].recordVersion,status,explanation:'测试提供的同一对象判断',sourceQuote:quote}]};}
function attach(s,r=report(s)){return e.attachSemanticReview(s,s.drafts[0].id,r,e.createReviewBinding(s,s.drafts[0].id));}
function decision(s){const d=s.drafts[0];return {factId:s.facts[0].id,recordVersion:s.facts[0].recordVersion,action:'accept_exception',reason:'作者检查后将这段保留为有意的例外',reviewHash:e.hash(JSON.stringify(d.modelReview))};}
function resolve(s){return e.resolveFactReview(s,s.drafts[0].id,decision(s),e.createReviewBinding(s,s.drafts[0].id));}
test('blue/red evidence-backed model contradiction blocks despite warning and empty general errors',()=>{const s=attach(fixture());assert.throws(()=>e.acceptDraft(s,s.drafts[0].id),{code:'FACT_DECISION_REQUIRED'});const row=e.getFactReviewGate(s,s.drafts[0].id)[0];assert.equal(row.provenanceValid,true);assert.equal(row.factSource.quote,blue);assert.equal(row.sourceQuote,'小舟提着小红纸灯。');assert.equal(row.blocking,true);});
test('unrelated settings use same structural policy without keyword hardcoding',()=>{const s=attach(fixture('阿岚生于南城。','阿岚生于北城。'));assert.throws(()=>e.acceptDraft(s,s.drafts[0].id),{code:'FACT_DECISION_REQUIRED'});});
for(const [name,text,status,quote] of [['negation','小舟没有提红纸灯。','consistent','小舟没有提红纸灯。'],['dialogue','“这灯是红的。”陌生人撒谎说。','not_applicable','“这灯是红的。”陌生人撒谎说。'],['hypothesis','假如那盏灯是红的，他会认错吗？','unknown','假如那盏灯是红的，他会认错吗？'],['unmentioned','风从山谷吹来。','not_applicable','']])test(`${name}: supplied model classification is preserved, not inferred from keywords`,()=>{let s=fixture(text);s=attach(s,report(s,status,quote));assert.equal(e.getFactReviewGate(s,s.drafts[0].id)[0].status,status);if(status==='unknown')assert.throws(()=>e.acceptDraft(s,s.drafts[0].id),{code:'FACT_DECISION_REQUIRED'});else assert.equal(e.acceptDraft(s,s.drafts[0].id).drafts[0].status,'ACCEPTED');});
test('missing fact assessment is unknown, distinct from explicit not_applicable',()=>{let s=fixture();const r=report(s);delete r.factChecks;s=attach(s,r);assert.equal(e.getFactReviewGate(s,s.drafts[0].id)[0].assessmentOrigin,'missing');assert.throws(()=>e.acceptDraft(s,s.drafts[0].id),{code:'FACT_DECISION_REQUIRED'});});
test('wrong fact identity/version, duplicate, invented quote, severity downgrade rejected',()=>{const s=fixture(),r=report(s);for(const change of [c=>c.factId='elsewhere',c=>c.recordVersion++,c=>c.sourceQuote='不存在',c=>c.severity='warning',c=>c.sourceQuote='']){const changed=structuredClone(r);change(changed.factChecks[0]);assert.throws(()=>attach(s,changed),{code:'INVALID_FACT_REVIEW'});}r.factChecks.push(r.factChecks[0]);assert.throws(()=>attach(s,r),{code:'INVALID_FACT_REVIEW'});});
test('unverifiable fact provenance remains unknown even if model says consistent',()=>{let s=fixture();s.facts[0].source.quote='不存在的原文';s=attach(s,report(s,'consistent'));assert.equal(e.getFactReviewGate(s,s.drafts[0].id)[0].status,'unknown');assert.throws(()=>e.acceptDraft(s,s.drafts[0].id),{code:'FACT_DECISION_REQUIRED'});});
test('explicit exception has rationale, evidence and review binding, audit survives acceptance without changing Canon',()=>{let s=attach(fixture()),id=s.drafts[0].id;const facts=structuredClone(s.facts);assert.throws(()=>e.resolveFactReview(s,id,{...decision(s),reason:''},e.createReviewBinding(s,id)),{code:'FACT_DECISION_REQUIRED'});s=resolve(s);assert.equal(e.getFactReviewGate(s,id)[0].resolved,true);s=e.acceptDraft(s,id);assert.deepEqual(s.facts,facts);assert.equal(s.commits.at(-1).factDecisions[0].factSource.quote,blue);assert.equal(s.commits.at(-1).factDecisions[0].sourceQuote,'小舟提着小红纸灯。');});
test('exception never overrides separate model error',()=>{let s=fixture(),r=report(s);r.issues[0].severity='error';s=resolve(attach(s,r));assert.throws(()=>e.acceptDraft(s,s.drafts[0].id),{code:'SEMANTIC_REVIEW_ERRORS'});});
test('edit, re-review and review tamper invalidate exception',()=>{const s=resolve(attach(fixture())),id=s.drafts[0].id;const changed=e.editDraft(s,id,'修改后的正文。');assert.deepEqual(changed.drafts[0].factDecisions,[]);const rereview=attach(s);assert.deepEqual(rereview.drafts[0].factDecisions,[]);assert.throws(()=>e.acceptDraft(rereview,id),{code:'FACT_DECISION_REQUIRED'});const tamper=structuredClone(s);tamper.drafts[0].modelReview.factChecks[0].status='consistent';assert.throws(()=>e.acceptDraft(tamper,id),{code:'SEMANTIC_REVIEW_REQUIRED'});});
test('modal decision cannot attach to changed draft/project/review',()=>{const s=attach(fixture()),id=s.drafts[0].id,binding=e.createReviewBinding(s,id),instruction=decision(s);for(const change of [t=>t.projectId='other',t=>t.drafts[0].revision++,t=>t.drafts[0].runId='other',t=>t.drafts[0].modelReview.summary+='new']){const next=structuredClone(s);change(next);assert.throws(()=>e.resolveFactReview(next,id,instruction,binding),{code:'STALE_FACT_DECISION'});}});
test('author superseding fact invalidates old draft/decision; new checks use new recordVersion',()=>{let s=resolve(attach(fixture())),id=s.drafts[0].id;s=e.saveRevision(s,'ch1','小舟的纸灯是红色的。',s.chapters[0].revision);s=e.commitPatch(s,e.proposeCustomPatch(s,'ch1',{intent:'author_fact',targetFactId:s.facts[0].id,statement:'小舟的纸灯是红色的。'}));assert.equal(s.facts[0].recordVersion,2);assert.throws(()=>e.acceptDraft(s,id),{code:'REVIEW_REQUIRED'});s=e.stageProviderDraft(s,{text:'小舟提着红纸灯。',context:e.getContext(s),provider:{id:'test',isLive:true}},'ch2');const d=s.drafts.at(-1);s=e.reviewDraft(s,d.id);const r={...report(s),factChecks:[{...report(s).factChecks[0],status:'consistent',sourceQuote:d.text}],issues:[]};s=e.attachSemanticReview(s,d.id,r,e.createReviewBinding(s,d.id));assert.equal(e.acceptDraft(s,d.id).drafts.at(-1).status,'ACCEPTED');});
test('JSON restore preserves bound decision; altered evidence/hash fails closed',()=>{const s=JSON.parse(JSON.stringify(resolve(attach(fixture())))),id=s.drafts[0].id;assert.equal(e.acceptDraft(s,id).drafts[0].status,'ACCEPTED');s.drafts[0].factDecisions[0].reviewHash='wrong';assert.throws(()=>e.acceptDraft(s,id),{code:'FACT_DECISION_REQUIRED'});});
test('rendering stale/historical ledgers survives a superseded fact and retains accepted decision evidence',()=>{let s=resolve(attach(fixture())),id=s.drafts[0].id;s=e.acceptDraft(s,id);assert.equal(e.getFactReviewGate(s,id)[0].resolved,true);s=e.saveRevision(s,'ch1','小舟的纸灯是红色的。',s.chapters[0].revision);s=e.commitPatch(s,e.proposeCustomPatch(s,'ch1',{intent:'author_fact',targetFactId:s.facts[0].id,statement:'小舟的纸灯是红色的。'}));assert.equal(e.getFactReviewGate(s,id)[0].factSource.quote,blue);const pending=attach(fixture());pending.facts[0].recordVersion++;assert.equal(e.getFactReviewGate(pending,pending.drafts[0].id)[0].stale,true);});
