/** Server boundary contracts. Untrusted JSON is unknown until the runtime guards pass. */
export type UnknownRecord = Record<string, unknown>;
export type AgentAction = 'interview' | 'planStory' | 'generateChapter' | 'generateProse' | 'reviseProse' | 'interpretRevision' | 'auditMemoryCandidate' | 'reviewChapter' | 'extractMemory';
export type AnswerKey = 'protagonist' | 'tone' | 'pov' | 'goal' | 'boundaries';
export type StoryInput = {idea: string; title?: string; answers?: Partial<Record<AnswerKey, string>>} & Partial<Record<AnswerKey, string>>;
export type ContextSource = {chapterId: string; revision: number; text: string};
/** Additional context and fact data remain unknown: they are reference material. */
export type AgentContext = {projectId: string; version: number; sources: ContextSource[]; facts?: unknown} & UnknownRecord;
export type GenerationInput = {project: {idea: string; projectId: string; outline: unknown[]} & UnknownRecord; chapterIndex: number; chapterId?: string; context: AgentContext};
export type RevisionInput = {text: string; instruction: string; chapterId: string; context: AgentContext};
export type InterpretationInput = {beforeText: string; afterText: string; chapterId: string; context: AgentContext};
export type MemoryCandidateInput = {candidateId: string; label: string; sourceQuote: string};
export type TextContextInput = {text: string; chapterId: string; context: AgentContext; memoryCandidates?: MemoryCandidateInput[]};
export type AuditInput = {label: string; sourceQuote: string};
export type AgentInputs = {
 interview: StoryInput; planStory: StoryInput; generateChapter: GenerationInput; generateProse: GenerationInput;
 reviseProse: RevisionInput; interpretRevision: InterpretationInput; auditMemoryCandidate: AuditInput; reviewChapter: TextContextInput; extractMemory: TextContextInput;
};
export type ValidatedRequest = {[A in AgentAction]: {action: A; input: AgentInputs[A]}}[AgentAction];
export type SupportStatus = 'supported' | 'unsupported' | 'unknown';
export type FactStatus = 'consistent' | 'contradiction' | 'not_applicable' | 'unknown';
export type Evidence = {label: string; sourceQuote: string};
export type IndexedEvidence = Evidence & {sourceParagraphIndex?: number};
export type ExtractedEvidence = Evidence & {sourceParagraphIndex: number; sourceStart: number; sourceEnd: number};
export type ProseOutput = {text: string; chapterId: string};
export type ChapterOutput = ProseOutput & {staging: IndexedEvidence[]; reviewNotes: string[]};
export type MemoryOutput = {staging: ExtractedEvidence[]; reviewNotes: string[]};
export type AuditOutput = {status: SupportStatus; explanation: string};
export type InterviewQuestion = {key: AnswerKey; title: string; hint: string; placeholder: string; options?: string[]};
export type InterviewOutput = {questions: InterviewQuestion[]; summary: string};
export type Scene = {time: string; location: string; participants: string[]; allowedReveal: string; forbiddenReveal: string; preconditions: string[]};
export type CreativeChapter = {title: string; goal: string; conflict: string; knowledgeDelta: string; exitState: string; emotionalArc: string; scene: Scene};
export type OutlineChapter = CreativeChapter & {id: string; pov: string; number?: number; status?: 'planned'; provenance?: string};
export type ContractFieldKey = 'premise' | 'protagonist' | 'emotionalDirection' | 'pov' | 'desire' | 'obstacle' | 'coreQuestion' | 'boundaries' | 'opening';
export type ContractField = {key: ContractFieldKey; label: string; value: string; status: 'proposed' | 'confirmed' | 'deferred'};
export type StoryContract = {fields: ContractField[]; premise: string; protagonist: string; emotionalDirection: string; pov: string; desire: string; boundaries: string; unresolved: string[]; schemaVersion?: 1; status?: 'proposal'; provenance?: ProviderIdentity};
export type PlanOutput = {contract: StoryContract; outline: OutlineChapter[]};
export type InterpretationOutput = {summary: string; intents: Array<'local_prose' | 'canon_update' | 'knowledge_update' | 'ambiguous'>; questions: string[]; suggestedFacts: Evidence[]};
export type ReviewOutput = {summary: string; issues: Array<{severity: 'error' | 'warning'; explanation: string; sourceQuote: string}>; checks: string[]; factChecks?: Array<{factId: string; recordVersion: number; status: FactStatus; explanation: string; sourceQuote: string}>; memoryChecks?: Array<{candidateId: string; status: SupportStatus; explanation: string}>};
export type AgentOutputs = {interview: InterviewOutput; planStory: PlanOutput; generateChapter: ChapterOutput; generateProse: ProseOutput; reviseProse: ProseOutput; interpretRevision: InterpretationOutput; auditMemoryCandidate: AuditOutput; reviewChapter: ReviewOutput; extractMemory: MemoryOutput};
export type Usage = Partial<Record<'promptTokens' | 'completionTokens' | 'totalTokens' | 'reasoningTokens', number>>;
export type ResponseDiagnostics = Usage & {finishReason: 'length'; finalContentPresent: boolean; reasoningContentPresent: boolean};
export type ProviderIdentity = {id: 'openai-compatible'; label: string; isLive: true; model: string; usage?: Usage};
export type AgentResult = {[A in AgentAction]: AgentOutputs[A] & {provider: ProviderIdentity}}[AgentAction];
export type Environment = Record<string, string | undefined>;
export type ProviderConfig = {reasoningEffort?: string; thinkingMode?: string; enabled: boolean; configured: boolean; endpoint: string | null; host: string | null; model: string | null; key: string | null; maxTokens: number | null; maxCalls: number | null};
export type ConfiguredProvider = ProviderConfig & {configured: true; endpoint: string; host: string; model: string; key: string; maxTokens: number; maxCalls: number};
export type ServiceStatus = {configured: boolean; liveEnabled: boolean; model: string | null; baseHost: string | null; callsUsed: number; maxCalls: number | null; maxOutputTokens: number | null};
export type RunOptions = {signal?: AbortSignal};
export type AgentService = {status(): ServiceStatus; run(action: unknown, input: unknown, options?: RunOptions): Promise<AgentResult>};
export type AgentServiceOptions = {env?: Environment; fetchImpl?: typeof fetch; timeoutMs?: number; now?: () => number};
export type ProviderRequestInput = {endpoint: string; key: string; body: string; signal: AbortSignal; sessionId?: string};
export type ProviderRequest = {url: string; options: RequestInit};
export type ProviderCategory = 'authentication' | 'permission' | 'quota' | 'rate_limit' | 'model_unavailable' | 'unsupported_parameter' | 'context_limit' | 'invalid_request' | 'upstream_unavailable' | 'unknown';
export type HttpCategory = ProviderCategory | 'payment_required' | 'not_found' | 'timeout' | 'request_too_large';
export type TransportDiagnostics = {httpStatus: number | null; httpCategory: HttpCategory; providerCategory: ProviderCategory; bodyState: 'unavailable' | 'aborted' | 'too_large' | 'invalid_json' | 'json'};
export type ErrorResponse = Pick<Response, 'status' | 'body'>;
export type OutputValidationArgs = {[A in AgentAction]: [action: A, out: unknown, input: AgentInputs[A]]}[AgentAction];
