import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import * as engine from '../src/domain/engine.js';

// Browser tests consume retained fictional prose; all semantic judgments here are mocks.
const retainedProse=JSON.parse(readFileSync(new URL('../eval/history/prose-pipeline-v1/completed-02.json',import.meta.url),'utf8'));
const retainedExtraction=JSON.parse(readFileSync(new URL('../eval/history/prose-pipeline-v1/completed-03.json',import.meta.url),'utf8'));
const provider={id:'browser-mock',isLive:true},KEY='nexusscribe.demo.v1';
const text='阿澄把木钥匙放在桌上。\n她第二天才打开北门。\n远处的铜铃响了一声。';
const entries=[{label:'阿澄把木钥匙放在桌上，然后打开北门。',sourceParagraphIndex:0},{label:'她当天打开北门并找到了失踪的朋友。',sourceParagraphIndex:1},{label:'远处的铜铃响了一声。',sourceParagraphIndex:2}];
function fixture({prose=text,staging=entries,statuses=['unsupported',null,'supported'],projectId='memory-browser',isolated=true}={}){
 let s=engine.createProjectFromConfig({projectId,title:'逐条记忆审阅'});s=engine.stageProseDraft(s,{text:prose,provider,context:engine.getContext(s)},'ch1');const id=s.drafts[0].id;s=engine.beginMemoryExtraction(s,id);s=engine.attachMemoryExtraction(s,id,{staging,provider,reviewNotes:[]},engine.createExtractionBinding(s,id));s=engine.reviewDraft(s,id);s=engine.attachSemanticReview(s,id,{summary:'合成测试审阅，非语义精度证据',issues:[],checks:[],factChecks:[],memoryChecks:engine.createMemoryReviewInput(s,id).flatMap((item,i)=>statuses[i]?[{candidateId:item.candidateId,status:statuses[i],explanation:statuses[i]==='supported'?'完整原文支持该标签':'标签包含所引段落未支持的另一项主张'}]:[]),provider},engine.createReviewBinding(s,id));if(isolated){for(const [i,item] of engine.createMemoryReviewInput(s,id).entries()){if(!statuses[i])continue;s=engine.beginMemorySupportAssessment(s,id,item.candidateId);s=engine.attachMemorySupportAssessment(s,id,item.candidateId,{status:statuses[i],explanation:statuses[i]==='supported'?'独立原文支持标签':'独立原文不支持完整标签',provider},engine.createMemorySupportBinding(s,id,item.candidateId))}}return s;
}
const workspace=state=>({format:1,serial:0,state,editing:{},patch:null,providerMode:'server'});
const candidate=(page,n)=>page.getByRole('article',{name:new RegExp(`^候选记忆 ${n}：`)});
const control=(page,action,n)=>page.getByRole('button',{name:new RegExp(`^${action}候选记忆 ${n}：`)});
const state=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).state,KEY);
async function mount(page,s=fixture(),extraWorkspace={}){
 await page.addInitScript(({key,data})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(data))},{key:KEY,data:{...workspace(s),...extraWorkspace}});await page.goto('/');await expect(page).toHaveTitle('NexusScribe · 雾港来信');
 await expect(page.locator('.draft-prose')).toBeVisible();await expect(page.locator('.draft-prose')).toHaveText(s.drafts[0].text);
 const candidates=page.getByLabel('候选记忆逐条选择');await expect(candidates).toBeAttached();await expect(candidates.locator('[data-candidate-id]')).toHaveCount(s.drafts[0].staging.length);
 await expect(page.locator('vite-error-overlay')).toHaveCount(0);
}
function health(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});return errors}
async function evidence(page,testInfo,label){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const path=testInfo.outputPath(`${label}.png`);await page.screenshot({path,fullPage:true,animations:'disabled'});await testInfo.attach(label,{path,contentType:'image/png'})}
async function accept(page){await page.getByRole('button',{name:'接受此版本'}).click();await expect(page.getByRole('dialog',{name:'确认接受候选稿与已选记忆'})).toBeVisible();expect((await state(page)).drafts[0].status).not.toBe('ACCEPTED');await page.getByRole('button',{name:'确认接受正文与所选记忆'}).click();expect((await state(page)).drafts[0].status).toBe('ACCEPTED')}
test.beforeEach(async({page,context})=>{await context.route('**/*',async route=>{const url=new URL(route.request().url());if(['127.0.0.1','localhost'].includes(url.hostname))await route.continue();else await route.abort('blockedbyclient')});await page.route('**/api/**',route=>route.fulfill({status:503,json:{error:{message:'未配置外部模型，禁止真实请求'}}}))});

test('retained paraphrase is never verified; author may reject it and keep exact reply paragraph',async({page},testInfo)=>{
 const errors=health(page),original=retainedExtraction.staging[1],reply=retainedExtraction.staging[2];await mount(page,fixture({prose:retainedProse.text,staging:[original,reply],statuses:['unsupported','supported']}));
 await expect(candidate(page,1).getByLabel('完整候选原文引用')).toHaveText(original.sourceQuote);await expect(candidate(page,1)).toContainText(original.label);await expect(control(page,'保留原文摘录',1)).toBeEnabled();await expect(page.getByRole('button',{name:'接受此版本'})).toBeDisabled();await evidence(page,testInfo,'retained-label-full-evidence');
 await control(page,'拒绝',1).click();await control(page,'保留原文摘录',2).click();await expect(page.getByLabel('候选记忆选择汇总')).toContainText('已选 1 / 2');await accept(page);const s=await state(page);expect(s.events).toHaveLength(1);expect(s.events[0].originalLabel).toBe(reply.label);expect(s.events[0].source.quote).toBe(reply.sourceQuote);expect(s.chapters[0].text).toBe(retainedProse.text);expect(s.drafts[0].staging).toHaveLength(2);await page.reload();await expect(page.getByText('作者已拒绝 · 不会提交')).toBeVisible();expect(errors).toEqual([]);
});

test('reject-all accepts prose with zero status or model requests even without candidate audits',async({page},testInfo)=>{
 const errors=health(page);let requests=0;page.on('request',request=>{if(new URL(request.url()).pathname.startsWith('/api/'))requests++});await mount(page,fixture({isolated:false}));await expect(control(page,'保留原文摘录',1)).toBeEnabled();await expect(control(page,'保留原文摘录',2)).toBeEnabled();await expect(page.getByRole('button',{name:'接受此版本'})).toBeDisabled();await page.getByRole('button',{name:'全部拒绝候选记忆 · 不调用模型'}).click();await page.getByRole('button',{name:'接受此版本'}).click();const dialog=page.getByRole('dialog',{name:'确认接受候选稿与已选记忆'});await expect(dialog).toContainText('提交 0 条候选记忆');await expect(dialog.getByRole('button',{name:'返回核对'})).toBeFocused();await evidence(page,testInfo,'reject-all-zero-request-confirmation');await dialog.getByRole('button',{name:'返回核对'}).click();expect((await state(page)).events).toHaveLength(0);await accept(page);expect((await state(page)).events).toHaveLength(0);expect((await state(page)).chapters[0].text).toBe(text);expect(requests).toBe(0);expect(errors).toEqual([]);
});

test('actual baseline accepted choices stay visible and unverified after reload',async({page},testInfo)=>{
 const errors=health(page),legacy=JSON.parse(readFileSync(new URL('../tests/fixtures/legacy-accepted-memory.json',import.meta.url),'utf8')).workspace.state;
 let requests=0;page.on('request',request=>{if(new URL(request.url()).pathname.startsWith('/api/'))requests++});
 await mount(page,legacy);
 for(const n of [1,2]){await expect(candidate(page,n)).toContainText('历史例外保留 · 未验证转述');await expect(candidate(page,n)).toContainText(`旧版作者理由 ${n}`);}
 for(const n of [3,4])await expect(candidate(page,n)).toContainText('作者已拒绝 · 不会提交');
 await expect(page.getByText('尚未决定 · 阻塞接受',{exact:true})).toHaveCount(0);
 expect((await state(page)).drafts[0].memoryDecisions).toEqual(legacy.drafts[0].memoryDecisions);
 await page.reload();await expect(candidate(page,1)).toContainText('旧版作者理由 1');
 expect((await state(page)).events).toEqual(legacy.events);expect(requests).toBe(0);
 await evidence(page,testInfo,'actual-legacy-accepted-choices-unverified');expect(errors).toEqual([]);
});

test('even a false-supported paraphrase requires checkbox and reason, supports cancellation, and remains author-attested',async({page},testInfo)=>{
 const errors=health(page);await mount(page,fixture({statuses:['supported','supported','supported']}));const before=await state(page);for(const item of engine.getMemoryReviewGate(before,before.drafts[0].id)){expect(item.canKeep).toBe(false);expect(item.canOverride).toBe(false);expect(item.canKeepQuote).toBe(true);expect(item.canAttest).toBe(true)}await expect(page.getByRole('button',{name:/^保留候选记忆 /})).toHaveCount(0);
 await control(page,'作者确认未验证转述',1).click();const dialog=page.getByRole('dialog',{name:'作者确认未验证转述'}),confirm=dialog.getByRole('button',{name:'确认保留未验证转述'}),checkbox=dialog.getByLabel('我理解这条转述未经验证');await expect(dialog).toContainText('未经验证');await expect(dialog.getByLabel('完整候选原文引用')).toHaveText(text.split('\n')[0]);await expect(dialog.getByLabel('作者确认理由')).toBeFocused();await expect(confirm).toBeDisabled();await checkbox.check();await expect(confirm).toBeDisabled();await dialog.getByLabel('作者确认理由').fill('   ');await expect(confirm).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(control(page,'作者确认未验证转述',1)).toBeFocused();expect((await state(page)).drafts[0].memoryDecisions).toHaveLength(0);
 await control(page,'作者确认未验证转述',1).click();await dialog.getByLabel('作者确认理由').fill('理由不能代替明确勾选声明');await expect(confirm).toBeDisabled();await checkbox.check();await expect(confirm).toBeEnabled();await dialog.getByRole('button',{name:'取消作者确认'}).click();expect((await state(page)).drafts[0].memoryDecisions).toHaveLength(0);
 await control(page,'作者确认未验证转述',1).click();await expect(checkbox).not.toBeChecked();await dialog.getByLabel('作者确认理由').fill('作者结合下一段明确承担跨段标签准确性');await checkbox.check();await confirm.focus();await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'关闭作者确认未验证转述'})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(confirm).toBeFocused();await evidence(page,testInfo,'attestation-full-evidence-checkbox-and-reason');await confirm.click();await expect(candidate(page,1)).toContainText('未经验证');await control(page,'拒绝',2).click();await control(page,'拒绝',3).click();await accept(page);const current=await state(page),decision=current.drafts[0].memoryDecisions[0];expect(current.events).toHaveLength(1);expect(decision.action).toBe('attest_keep');expect(decision.selectionProtocol).toBe('quote-grounded-memory-v1');expect(decision.attestation).toEqual({protocol:'quote-grounded-memory-v1',accepted:true,statement:engine.MEMORY_ATTESTATION_STATEMENT});expect(current.events[0].label).toBe(entries[0].label);expect(current.events[0].memoryKind).toBe('author_attested_paraphrase');expect(current.events[0].memoryTrust).toBe('author_attested_unverified');expect(engine.getContext(current).events[0]).toEqual(expect.objectContaining({label:entries[0].label,kind:'author_attested_paraphrase',trust:'author_attested_unverified',memoryDecision:expect.objectContaining({action:'attest_keep',advisory:true})}));await page.reload();expect((await state(page)).events[0].memoryTrust).toBe('author_attested_unverified');expect(errors).toEqual([]);
});

for(const mutation of ['edit','rereview','import'])test(`an open attestation cannot authorize state after ${mutation}`,async({page},testInfo)=>{
 const errors=health(page);await mount(page);await control(page,'作者确认未验证转述',1).click();await page.getByLabel('作者确认理由').fill('仅对打开时的版本有效');await page.getByLabel('我理解这条转述未经验证').check();
 // Deliberately trigger background controls to simulate an external state transition while a dialog remains open.
 if(mutation==='edit'){await page.getByRole('button',{name:'编辑此稿'}).evaluate(el=>el.click());await page.getByLabel('编辑候选稿').evaluate((el,value)=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}))},text+'\n追加版本');await page.getByRole('button',{name:'保存候选稿修改'}).evaluate(el=>el.click());}
 if(mutation==='rereview'){let release,request;const pending=new Promise(resolve=>{release=resolve});await page.route('**/api/agent',async route=>{request=route.request().postDataJSON();await pending;await route.fulfill({json:{output:{summary:'重新审阅',issues:[],checks:[],factChecks:[],memoryChecks:[],provider}}})});await page.getByRole('button',{name:'审查候选稿'}).evaluate(el=>el.click());await expect.poll(()=>request?.action).toBe('reviewChapter');expect(request.input).not.toHaveProperty('memoryCandidates');await expect(page.getByRole('button',{name:'确认保留未验证转述'})).toBeDisabled();await expect(control(page,'拒绝',1)).toBeDisabled();release();await expect(page.getByLabel('模型任务状态')).toContainText('结果已返回');}
 if(mutation==='import'){await page.getByLabel('导入备份').setInputFiles({name:'fictional-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(workspace(fixture({projectId:'import-source'}))))});await page.getByRole('button',{name:'确认作为新项目导入'}).click();expect((await state(page)).projectId).not.toBe('memory-browser');}
 await page.getByRole('button',{name:'确认保留未验证转述'}).click();await expect(page.getByRole('status')).toContainText(/变化|过期|重新|找不到|审查/);const s=await state(page);expect(s.drafts[0].memoryDecisions).toHaveLength(0);expect(s.events).toHaveLength(0);await evidence(page,testInfo,`stale-attestation-${mutation}`);expect(errors).toEqual([]);
});

test('successful empty extraction is distinct from a failed extraction',async({page},testInfo)=>{
 const errors=health(page);await mount(page,fixture({staging:[],statuses:[]}));await expect(page.getByLabel('无候选记忆')).toContainText('提取成功 · 返回 0 条');await accept(page);expect((await state(page)).events).toHaveLength(0);await evidence(page,testInfo,'empty-extraction-accepted');expect(errors).toEqual([]);
});


test('failed extraction keeps prose and cannot be mistaken for successful zero-memory output',async({page},testInfo)=>{
 const errors=health(page);let failed=fixture({staging:[],statuses:[]});const id=failed.drafts[0].id;failed=engine.beginMemoryExtraction(failed,id);failed=engine.markExtractionFailure(failed,id,engine.createExtractionBinding(failed,id));await mount(page,failed);await expect(page.getByLabel('候选记忆提取状态')).toContainText('提取未完成');await expect(page.getByLabel('无候选记忆')).toHaveCount(0);await expect(page.getByRole('button',{name:'接受此版本'})).toBeDisabled();expect((await state(page)).drafts[0].text).toBe(text);await evidence(page,testInfo,'extraction-failed');expect(errors).toEqual([]);
});


for(const extraction of ['failed','populated'])test(`rejecting ${extraction} extraction shows archived cancellation, never successful empty output`,async({page},testInfo)=>{
 const errors=health(page);let initial=fixture(extraction==='failed'?{staging:[],statuses:[]}:{});const id=initial.drafts[0].id;
 if(extraction==='failed'){initial=engine.beginMemoryExtraction(initial,id);initial=engine.markExtractionFailure(initial,id,engine.createExtractionBinding(initial,id))}
 await mount(page,initial);if(extraction==='populated')await control(page,'拒绝',1).click();const prior=(await state(page)).drafts[0];await page.getByRole('button',{name:'拒绝此稿'}).click();
 await expect(page.getByLabel('候选记忆提取状态')).toContainText('候选稿已拒绝');await expect(page.getByLabel('候选记忆提取状态')).toContainText('提取已取消');await expect(page.getByLabel('候选记忆已归档')).toBeVisible();await expect(page.getByLabel('无候选记忆')).toHaveCount(0);await expect(page.getByLabel('候选记忆提取状态')).not.toContainText('已提取');
 const s=await state(page),draft=s.drafts[0],archive=draft.memoryArchives.findLast(entry=>entry.reason==='draft_rejected');expect(draft.status).toBe('REJECTED');expect(draft.extraction.status).toBe('cancelled');expect(draft.staging).toHaveLength(0);expect(s.events).toHaveLength(0);expect(draft.proseVersions).toEqual(prior.proseVersions);expect(archive.candidates).toEqual(prior.staging);expect(archive.extractionSnapshot.status).toBe(prior.extraction.status);expect(archive.decisions).toEqual(prior.memoryDecisions);
 await page.reload();await expect(page.getByLabel('候选记忆提取状态')).toContainText('候选稿已拒绝');await expect(page.getByLabel('无候选记忆')).toHaveCount(0);await evidence(page,testInfo,`rejected-${extraction}-archive`);expect(errors).toEqual([]);
});


test('offline same-text structural rereview invalidates an open attestation before any decision exists',async({page},testInfo)=>{
 const errors=health(page);let initial=engine.createProjectFromConfig({projectId:'offline-rereview-browser'});initial=engine.stageProviderDraft(initial,{text,provider:{id:'offline-template',isLive:false},context:engine.getContext(initial),staging:[{label:entries[0].label,sourceQuote:text.split('\n')[0]}]},'ch1');initial=engine.reviewDraft(initial,initial.drafts[0].id);let requests=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/api/agent')requests++});await mount(page,initial);const prior=(await state(page)).drafts[0];expect(prior.memoryDecisions).toHaveLength(0);expect(prior.modelReview).toBeNull();await control(page,'作者确认未验证转述',1).click();await page.getByLabel('作者确认理由').fill('只同意打开窗口时的离线审阅');await page.getByLabel('我理解这条转述未经验证').check();await page.getByRole('button',{name:'审查候选稿'}).evaluate(el=>el.click());await expect.poll(async()=>(await state(page)).drafts[0].memoryReviewEpoch).toBeGreaterThan(prior.memoryReviewEpoch);
 const current=(await state(page)).drafts[0];expect(current.text).toBe(prior.text);expect(current.revision).toBe(prior.revision);expect(current.memoryDecisions).toHaveLength(0);expect(current.modelReview).toBeNull();await page.getByRole('button',{name:'确认保留未验证转述'}).click();await expect(page.getByRole('status')).toContainText(/变化|过期|重新/);expect((await state(page)).drafts[0].memoryDecisions).toHaveLength(0);expect((await state(page)).events).toHaveLength(0);expect(requests).toBe(0);await evidence(page,testInfo,'offline-rereview-stale-attestation');expect(errors).toEqual([]);
});

const availableBudget={configured:true,liveEnabled:true,callsUsed:2,maxCalls:10};
test('bundled supported stays advisory; optional audits send original label and quote without authorizing paraphrase',async({page},testInfo)=>{
 const errors=health(page),original=retainedExtraction.staging[1],reply=retainedExtraction.staging[2],requests=[];let statusReads=0;
 await page.route('**/api/status',route=>{statusReads++;return route.fulfill({json:{...availableBudget,callsUsed:2+requests.length}})});
 await page.route('**/api/agent',async route=>{const request=route.request().postDataJSON();requests.push(request);expect(request.action).toBe('auditMemoryCandidate');expect(Object.keys(request.input).sort()).toEqual(['label','sourceQuote']);const unsupported=request.input.label===original.label;await route.fulfill({json:{output:{status:unsupported?'unsupported':'supported',explanation:unsupported?'该条原文没有程岚的回应':'该条原文完整记录回应',provider}}})});
 await mount(page,fixture({prose:retainedProse.text,staging:[original,reply],statuses:['supported','supported'],isolated:false}));await expect(control(page,'保留原文摘录',1)).toBeEnabled();await expect(control(page,'保留原文摘录',2)).toBeEnabled();await expect(candidate(page,1).getByLabel('历史整章记忆判断')).toContainText('原文支持');await expect(page.getByLabel('独立核对调用预算')).toContainText('基础 3 次请求');await expect(page.getByLabel('独立核对调用预算')).toContainText('+ K 次');
 await control(page,'独立核对',1).click();await expect(candidate(page,1)).toContainText('该条原文没有程岚的回应');expect(requests).toHaveLength(1);expect(statusReads).toBe(1);expect(requests[0].input).toEqual({label:original.label,sourceQuote:original.sourceQuote});await expect(control(page,'保留原文摘录',1)).toBeEnabled();await expect(control(page,'保留原文摘录',2)).toBeEnabled();
 await control(page,'拒绝',1).click();await control(page,'独立核对',2).click();await expect(page.getByLabel('独立核对状态 2')).toContainText('已完成');await expect(control(page,'保留原文摘录',2)).toBeEnabled();expect(requests).toHaveLength(2);expect(requests[1].input).toEqual({label:reply.label,sourceQuote:reply.sourceQuote});await control(page,'保留原文摘录',2).click();await evidence(page,testInfo,'isolated-counterexample-two-field-audits');await accept(page);expect(requests).toHaveLength(2);expect((await state(page)).events).toHaveLength(1);expect((await state(page)).events[0].originalLabel).toBe(reply.label);expect(errors).toEqual([]);
});

test('gradual auditing and failed or cancelled target audits preserve other current choices',async({page},testInfo)=>{
 const errors=health(page);await page.route('**/api/status',route=>route.fulfill({json:availableBudget}));let requests=0,releaseAudit;const pending=new Promise(resolve=>{releaseAudit=resolve});
 await page.route('**/api/agent',async route=>{requests++;if(requests===1){await route.fulfill({json:{output:{status:'malformed',explanation:'合成格式错误',provider}}});return}await pending;await route.fulfill({json:{output:{status:'supported',explanation:'已取消的迟到判断',provider}}})});
 await mount(page);await control(page,'保留原文摘录',3).click();const selected=(await state(page)).drafts[0].memoryDecisions[0];await control(page,'独立核对',1).click();await expect(page.getByLabel('独立核对状态 1')).toContainText('失败');expect((await state(page)).drafts[0].memoryDecisions).toContainEqual(selected);await expect(control(page,'保留原文摘录',3)).toBeEnabled();
 await control(page,'独立核对',2).click();await expect.poll(()=>requests).toBe(2);await page.getByRole('button',{name:'取消请求'}).click();releaseAudit();await expect(page.getByLabel('独立核对状态 2')).toContainText('已取消');await expect(control(page,'保留原文摘录',2)).toBeEnabled();expect((await state(page)).drafts[0].memoryDecisions).toContainEqual(selected);await expect(control(page,'保留原文摘录',3)).toBeEnabled();await evidence(page,testInfo,'other-choice-survives-audit-failure');expect(errors).toEqual([]);
});

for(const blocked of ['exhausted','missing','disabled'])test(`isolated audit refuses ${blocked} server budget before any model dispatch`,async({page},testInfo)=>{
 const errors=health(page);let posts=0;await page.route('**/api/status',route=>route.fulfill({json:blocked==='exhausted'?{...availableBudget,callsUsed:10}:blocked==='disabled'?{...availableBudget,liveEnabled:false}:{configured:true,liveEnabled:true}}));await page.route('**/api/agent',route=>{posts++;return route.fulfill({json:{output:{status:'supported',explanation:'must not be requested',provider}}})});
 await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect(page.getByRole('status')).toContainText('未发送独立核对请求');await expect(control(page,'保留原文摘录',1)).toBeEnabled();expect(posts).toBe(0);expect((await state(page)).events).toHaveLength(0);await evidence(page,testInfo,`audit-budget-${blocked}`);expect(errors).toEqual([]);
});

for(const interruption of ['cancel','edit','unsaved','import'])test(`audit ${interruption} while budget read is pending prevents subsequent dispatch`,async({page},testInfo)=>{
 const errors=health(page);let releaseBudget,statusReads=0,posts=0;const pending=new Promise(resolve=>{releaseBudget=resolve});await page.route('**/api/status',async route=>{statusReads++;await pending;await route.fulfill({json:availableBudget})});await page.route('**/api/agent',route=>{posts++;return route.fulfill({json:{output:{status:'supported',explanation:'must not dispatch',provider}}})});await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect.poll(()=>statusReads).toBe(1);
 if(interruption==='cancel')await page.getByRole('button',{name:'取消请求'}).click();
 if(interruption==='unsaved')await page.getByLabel('章节正文').fill('尚未保存的新正文');
 if(interruption==='edit'){await page.getByRole('button',{name:'编辑此稿'}).click();await page.getByLabel('编辑候选稿').fill(text+'\n新版本');await page.getByRole('button',{name:'保存候选稿修改'}).click();}
 if(interruption==='import'){await page.getByLabel('导入备份').setInputFiles({name:'isolated-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(workspace(fixture({projectId:'preflight-import',isolated:false}))))});await page.getByRole('button',{name:'取消请求'}).evaluate(el=>el.click());await page.getByRole('button',{name:'确认作为新项目导入'}).click();}
 releaseBudget();await expect(page.getByLabel('模型任务状态')).toContainText(interruption==='unsaved'?'返回结果未采用':'已取消等待');expect(posts).toBe(0);expect((await state(page)).events).toHaveLength(0);await evidence(page,testInfo,`audit-preflight-${interruption}`);expect(errors).toEqual([]);
});

test('cancelled isolated result cannot replay into a new attempt',async({page},testInfo)=>{
 const errors=health(page);let requests=0,releaseOld;const oldPending=new Promise(resolve=>{releaseOld=resolve});await page.route('**/api/status',route=>route.fulfill({json:availableBudget}));await page.route('**/api/agent',async route=>{requests++;const old=requests===1;if(old)await oldPending;await route.fulfill({json:{output:{status:old?'supported':'unsupported',explanation:old?'旧判断不得重放':'当前独立引文不支持完整标签',provider}}})});await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect.poll(()=>requests).toBe(1);await page.getByRole('button',{name:'取消请求'}).click();await control(page,'独立核对',1).click();await expect(candidate(page,1)).toContainText('当前独立引文不支持完整标签');releaseOld();await expect(control(page,'保留原文摘录',1)).toBeEnabled();await expect(candidate(page,1)).not.toContainText('旧判断不得重放');expect(requests).toBe(2);expect((await state(page)).events).toHaveLength(0);await evidence(page,testInfo,'isolated-replay-guard');expect(errors).toEqual([]);
});

for(const mutation of ['edit','rereview','import'])test(`late isolated audit cannot cross ${mutation} boundaries`,async({page},testInfo)=>{
 const errors=health(page);let releaseAudit,auditCalls=0,oldReturned=false;const pending=new Promise(resolve=>{releaseAudit=resolve});await page.route('**/api/status',route=>route.fulfill({json:availableBudget}));await page.route('**/api/agent',async route=>{const request=route.request().postDataJSON();if(request.action==='reviewChapter'){expect(request.input).not.toHaveProperty('memoryCandidates');await route.fulfill({json:{output:{summary:'新的整章审阅没有独立记忆授权',issues:[],checks:[],factChecks:[],provider}}});return}expect(request.action).toBe('auditMemoryCandidate');auditCalls++;await pending;await route.fulfill({json:{output:{status:'supported',explanation:'旧审查结果不得移用',provider}}});oldReturned=true});await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect.poll(()=>auditCalls).toBe(1);
 if(mutation==='edit'){await page.getByRole('button',{name:'编辑此稿'}).click();await page.getByLabel('编辑候选稿').fill(text+'\n候选新版本');await page.getByRole('button',{name:'保存候选稿修改'}).click();}
 if(mutation==='rereview'){await page.getByRole('button',{name:'取消请求'}).click();await page.getByRole('button',{name:'审查候选稿'}).click();await expect(page.getByText('新的整章审阅没有独立记忆授权')).toBeVisible();}
 if(mutation==='import'){await page.getByRole('button',{name:'取消请求'}).click();await page.getByLabel('导入备份').setInputFiles({name:'audit-result-import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(workspace(fixture({projectId:'late-audit-import',isolated:false}))))});await page.getByRole('button',{name:'确认作为新项目导入'}).click();}
 releaseAudit();await expect.poll(()=>oldReturned).toBe(true);const current=await state(page);expect(current.events).toHaveLength(0);expect(current.drafts[0].memoryDecisions).toHaveLength(0);expect(engine.getMemoryReviewGate(current,current.drafts[0].id).every(item=>!item.canKeep&&item.auditState!=='complete')).toBe(true);await expect(page.getByText('旧审查结果不得移用')).toHaveCount(0);await evidence(page,testInfo,`isolated-late-${mutation}`);expect(errors).toEqual([]);
});

for(const announce of [true,false])test(`storage conflict during audit preflight blocks paid dispatch (${announce?'storage event':'serial recheck'})`,async({page},testInfo)=>{
 const errors=health(page);let releaseStatus,statusCalls=0,statusReturned=false,paidCalls=0;const pending=new Promise(resolve=>{releaseStatus=resolve});await page.route('**/api/status',async route=>{statusCalls++;await pending;await route.fulfill({json:availableBudget});statusReturned=true});await page.route('**/api/agent',route=>{paidCalls++;return route.fulfill({json:{output:{status:'supported',explanation:'must never dispatch',provider}}})});await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect.poll(()=>statusCalls).toBe(1);
 await page.evaluate(({key,announce})=>{const oldValue=localStorage.getItem(key),external=JSON.parse(oldValue);external.serial++;external.state.title='另一窗口的当前版本';const newValue=JSON.stringify(external);localStorage.setItem(key,newValue);if(announce)window.dispatchEvent(new StorageEvent('storage',{key,oldValue,newValue,storageArea:localStorage}))},{key:KEY,announce});releaseStatus();await expect.poll(()=>statusReturned).toBe(true);await expect(page.getByRole('alert')).toContainText('另一窗口');await expect(page.getByLabel('独立核对状态 1')).toContainText('已取消');await expect(control(page,'独立核对',1)).toBeDisabled();expect(paidCalls).toBe(0);expect((await state(page)).title).toBe('另一窗口的当前版本');await evidence(page,testInfo,`audit-storage-conflict-${announce?'event':'recheck'}`);expect(errors).toEqual([]);
});

for(const failure of ['QuotaExceededError','SecurityError'])test(`paid isolated result survives ${failure}, exports and retries without a new audit`,async({page},testInfo)=>{
 const errors=health(page);let releaseAudit,paidCalls=0;const pending=new Promise(resolve=>{releaseAudit=resolve});await page.route('**/api/status',route=>route.fulfill({json:availableBudget}));await page.route('**/api/agent',async route=>{paidCalls++;await pending;await route.fulfill({json:{output:{status:'supported',explanation:`VALID_RESULT_KEEP_ME_${failure}`,provider}}})});await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect.poll(()=>paidCalls).toBe(1);
 await page.evaluate(({key,failure})=>{window.auditOriginalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,value){if(k===key)throw new DOMException('synthetic paid result save failure',failure);return window.auditOriginalSetItem.call(this,k,value)}},{key:KEY,failure});releaseAudit();await expect(candidate(page,1)).toContainText(`VALID_RESULT_KEEP_ME_${failure}`);await expect(page.getByRole('alert')).toContainText('synthetic paid result save failure');await expect(page.getByRole('status')).toContainText('已保留在本窗口，但尚未安全保存');await expect(control(page,'独立核对',1)).toBeDisabled();expect(engine.getMemoryReviewGate(await state(page),(await state(page)).drafts[0].id)[0].auditState).toBe('pending');
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'导出当前内容（含暂存编辑）'}).click();const download=await downloaded,stream=await download.createReadStream();let raw='';for await(const chunk of stream)raw+=chunk;const exported=JSON.parse(raw);expect(raw).toContain(`VALID_RESULT_KEEP_ME_${failure}`);expect(engine.getMemoryReviewGate(exported.state,exported.state.drafts[0].id)[0].auditState).toBe('complete');await evidence(page,testInfo,`audit-paid-result-unsaved-${failure}`);
 await page.evaluate(()=>{Storage.prototype.setItem=window.auditOriginalSetItem});await page.getByRole('button',{name:'重试保存'}).click();await expect(page.getByRole('alert')).toHaveCount(0);expect(paidCalls).toBe(1);const saved=await state(page);expect(JSON.stringify(saved)).toContain(`VALID_RESULT_KEEP_ME_${failure}`);expect(engine.getMemoryReviewGate(saved,saved.drafts[0].id)[0].canKeepQuote).toBe(true);await page.reload();await expect(candidate(page,1)).toContainText(`VALID_RESULT_KEEP_ME_${failure}`);expect(paidCalls).toBe(1);expect(errors).toEqual([]);
});

for(const outcome of ['failed','cancelled'])test(`unsaved ${outcome} audit transition retries locally without restoring an old result`,async({page},testInfo)=>{
 const errors=health(page);let releaseAudit,paidCalls=0;const pending=new Promise(resolve=>{releaseAudit=resolve});await page.route('**/api/status',route=>route.fulfill({json:availableBudget}));await page.route('**/api/agent',async route=>{paidCalls++;await pending;await route.fulfill({json:{output:{status:outcome==='failed'?'invalid':'supported',explanation:'cancelled or invalid result must not attach',provider}}})});await mount(page,fixture({isolated:false}));await control(page,'独立核对',1).click();await expect.poll(()=>paidCalls).toBe(1);await page.evaluate(key=>{window.auditOriginalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,value){if(k===key)throw new DOMException('synthetic audit transition save failure','QuotaExceededError');return window.auditOriginalSetItem.call(this,k,value)}},KEY);if(outcome==='cancelled')await page.getByRole('button',{name:'取消请求'}).click();releaseAudit();await expect(page.getByLabel('独立核对状态 1')).toContainText(outcome==='cancelled'?'已取消':'失败');await expect(page.getByRole('alert')).toContainText('synthetic audit transition save failure');await expect(control(page,'独立核对',1)).toBeDisabled();await evidence(page,testInfo,`audit-unsaved-${outcome}`);await page.evaluate(()=>{Storage.prototype.setItem=window.auditOriginalSetItem});await page.getByRole('button',{name:'重试保存'}).click();await expect(page.getByRole('alert')).toHaveCount(0);const current=await state(page);expect(engine.getMemoryReviewGate(current,current.drafts[0].id)[0].auditState).toBe(outcome);expect(engine.getMemoryReviewGate(current,current.drafts[0].id)[0].canKeep).toBe(false);expect(paidCalls).toBe(1);expect(errors).toEqual([]);
});

test('health-only save failure after dispatch preserves the current paid audit for retry',async({page},testInfo)=>{
 const errors=health(page),initial=fixture({isolated:false});let releaseAudit,paidCalls=0;const pending=new Promise(resolve=>{releaseAudit=resolve});await page.route('**/api/status',route=>route.fulfill({json:availableBudget}));await page.route('**/api/agent',async route=>{paidCalls++;await pending;await route.fulfill({json:{output:{status:'supported',explanation:'PAID_RESULT_AFTER_HEALTH_ERROR',provider}}})});await mount(page,initial,{patch:engine.proposeCustomPatch(initial,'ch1',{intent:'local_prose'})});await control(page,'独立核对',1).click();await expect.poll(()=>paidCalls).toBe(1);await page.evaluate(key=>{window.auditOriginalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,value){if(k===key)throw new DOMException('health-only write failure','QuotaExceededError');return window.auditOriginalSetItem.call(this,k,value)}},KEY);await page.getByRole('button',{name:'关闭影响预览'}).click();await expect(page.getByRole('alert')).toContainText('health-only write failure');releaseAudit();await expect(candidate(page,1)).toContainText('PAID_RESULT_AFTER_HEALTH_ERROR');await expect(control(page,'独立核对',1)).toBeDisabled();await evidence(page,testInfo,'audit-health-only-error-retained');await page.evaluate(()=>{Storage.prototype.setItem=window.auditOriginalSetItem});await page.getByRole('button',{name:'重试保存'}).click();await expect(page.getByRole('alert')).toHaveCount(0);const current=await state(page);expect(JSON.stringify(current)).toContain('PAID_RESULT_AFTER_HEALTH_ERROR');expect(engine.getMemoryReviewGate(current,current.drafts[0].id)[0].canKeepQuote).toBe(true);expect(paidCalls).toBe(1);expect(errors).toEqual([]);
});

test('project switch archives cancelled audit state after a pending budget read',async({page},testInfo)=>{
 const errors=health(page);let releaseStatus,statusCalls=0,statusReturned=false,paidCalls=0;const pending=new Promise(resolve=>{releaseStatus=resolve});await page.route('**/api/status',async route=>{statusCalls++;await pending;await route.fulfill({json:availableBudget});statusReturned=true});await page.route('**/api/agent',route=>{paidCalls++;return route.fulfill({json:{output:{status:'supported',explanation:'must not dispatch',provider}}})});const initial=fixture({isolated:false});await mount(page,initial,{archived:[{state:engine.createProjectFromConfig({projectId:'audit-switch-target',title:'另一个故事'}),editing:{},patch:null}]});await control(page,'独立核对',1).click();await expect.poll(()=>statusCalls).toBe(1);await page.getByLabel('切换项目').selectOption('audit-switch-target');releaseStatus();await expect.poll(()=>statusReturned).toBe(true);const current=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);expect(current.state.projectId).toBe('audit-switch-target');const original=current.archived.find(project=>project.state.projectId===initial.projectId);expect(original.state.drafts[0].memorySupport.attempts.at(-1).state).toBe('cancelled');expect(paidCalls).toBe(0);await evidence(page,testInfo,'audit-switch-cancellation-archived');expect(errors).toEqual([]);
});


test('quote cards expand a partial candidate quote to the exact full paragraph without promoting its label',async({page},testInfo)=>{
 const errors=health(page),partial='把木钥匙放在桌上',label='阿澄证明木钥匙能打开所有门';let requests=0;page.on('request',request=>{if(new URL(request.url()).pathname.startsWith('/api/'))requests++});let initial=engine.createProjectFromConfig({projectId:'legacy-partial-browser'});initial=engine.stageProviderDraft(initial,{text,provider,context:engine.getContext(initial),staging:[{label,sourceQuote:partial}]},'ch1');initial=engine.reviewDraft(initial,initial.drafts[0].id);initial=engine.attachSemanticReview(initial,initial.drafts[0].id,{summary:'合成旧版部分引文审阅',issues:[],checks:[],factChecks:[],provider},engine.createReviewBinding(initial,initial.drafts[0].id));await mount(page,initial);await expect(candidate(page,1).getByLabel('完整候选原文引用')).toHaveText(partial);await expect(candidate(page,1).getByLabel('完整来源段落')).toHaveText(text.split('\n')[0]);await control(page,'保留原文摘录',1).click();await accept(page);const current=await state(page),event=current.events[0];expect(event.label).toBe('原文摘录 · 第 1 段');expect(event.originalLabel).toBe(label);expect(event.source.quote).toBe(text.split('\n')[0]);expect(event.memoryTrust).toBe('textual_presence_only');expect(current.drafts[0].memoryDecisions[0].action).toBe('keep_quote');expect(requests).toBe(0);await evidence(page,testInfo,'partial-quote-expanded-exact-paragraph');expect(errors).toEqual([]);
});
