import {test,expect} from '@playwright/test';
import {createInitialState} from '../src/domain/engine.js';
const KEY='nexusscribe.demo.v1',BACKUP=KEY+'.last-good';
const fixture=()=>({format:1,serial:3,state:createInitialState(),editing:{},patch:null});
test.beforeEach(async({context})=>{await context.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort())});
const errorsFor=page=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));return errors};
async function upload(page,data){await page.getByLabel('导入备份',{exact:true}).setInputFiles({name:'fictional-backup.json',mimeType:'application/json',buffer:Buffer.from(typeof data==='string'?data:JSON.stringify(data))})}
async function capture(page,testInfo,name){await page.screenshot({path:testInfo.outputPath(name+'.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)}
test('backup preview cancel, reject malformed, import as new, reload, preserve old editing',async({page},info)=>{
 const errors=errorsFor(page);await page.goto('/');await expect(page).toHaveTitle('NexusScribe · 雾港来信');await page.getByLabel('章节正文').fill('原项目的虚构暂存正文');const before=await page.evaluate(k=>localStorage.getItem(k),KEY);
 await upload(page,'{"format":99}');await expect(page.getByRole('alert')).toContainText('不兼容');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe(before);await page.getByRole('button',{name:'关闭导入错误'}).click();
 await upload(page,fixture());await expect(page.getByRole('dialog',{name:'备份导入预览'})).toContainText('3 个正文版本');await capture(page,info,'backup-preview');await page.getByRole('button',{name:'取消导入'}).click();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe(before);
 await upload(page,fixture());await page.getByRole('button',{name:'确认作为新项目导入'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);let saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);expect(saved.state.projectId).not.toBe('mist-harbor');expect(saved.state.importOrigin.original.state).toEqual(fixture().state);expect(saved.archived[0].editing.ch2).toBe('原项目的虚构暂存正文');await page.reload();await page.getByLabel('切换项目').selectOption('mist-harbor');await page.getByRole('navigation',{name:'章节'}).getByRole('button').nth(1).click();await expect(page.getByLabel('章节正文')).toHaveValue('原项目的虚构暂存正文');expect(errors).toEqual([]);
});
test('corrupt primary recovery cancel/confirm includes current edits and preserves bad bytes',async({page},info)=>{
 const errors=errorsFor(page);await page.goto('/');await page.evaluate(({KEY,BACKUP,data})=>{localStorage.setItem(KEY,'fictional broken JSON');localStorage.setItem(BACKUP,JSON.stringify(data))},{KEY,BACKUP,data:fixture()});await page.reload();await expect(page.getByRole('alert')).toContainText('主存储损坏');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('fictional broken JSON');await page.getByLabel('章节正文').fill('恢复过程中新增的虚构编辑');await page.getByRole('button',{name:'检查并恢复存储'}).click();await page.getByRole('button',{name:'取消恢复'}).click();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('fictional broken JSON');await capture(page,info,'recovery-blocked');await page.getByRole('button',{name:'检查并恢复存储'}).click();await page.getByRole('button',{name:'保留原始数据并确认恢复'}).click();expect(await page.evaluate(k=>localStorage.getItem(k+'.preserved'),KEY)).toBe('fictional broken JSON');await page.reload();await expect(page.getByLabel('章节正文')).toHaveValue('恢复过程中新增的虚构编辑');expect(errors).toEqual([]);
});
test('quota failure retains typed edits, exports them, retries and reloads',async({page},info)=>{
 const errors=errorsFor(page);await page.goto('/');await page.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Quota exhausted','QuotaExceededError')}});await page.getByLabel('章节正文').fill('配额失败时的虚构编辑');await expect(page.getByRole('alert')).toContainText('尚未安全保存');await expect(page.getByLabel('章节正文')).toHaveValue('配额失败时的虚构编辑');await capture(page,info,'quota-unsaved');const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'导出当前内容（含暂存编辑）'}).click();const dl=await downloaded;const stream=await dl.createReadStream();let raw='';for await(const chunk of stream)raw+=chunk;expect(JSON.parse(raw).editing.ch2).toBe('配额失败时的虚构编辑');await page.evaluate(()=>{Storage.prototype.setItem=window.originalSet});await page.getByRole('button',{name:'重试保存'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await page.reload();await expect(page.getByLabel('章节正文')).toHaveValue('配额失败时的虚构编辑');expect(errors).toEqual([]);
});
