import {errorMessage} from '../hooks/useModelTask.js';
import type {Patch, PatchOperation, SourceAnchor} from '../domain/types.js';
import type {validatePatch} from '../domain/engine.js';
interface PatchPanelProps {
 patch?: Patch | null;
 validation: ReturnType<typeof validatePatch> | null;
 onCommit: () => void;
 onClose: () => void;
}
const operationLabels: Record<string, string> = {set_relationship:'替代旧关系：陈默三年前见过死者',remove_evidence:'移除已删除的知识来源',append_author_fact:'记录作者确认的新设定',supersede_author_fact:'替代作者指定的已有设定'};
import {ArrowRight, Check, GitBranch, X, AlertCircle} from 'lucide-react';
export default function PatchPanel({patch,validation,onCommit,onClose}: PatchPanelProps){return <section className="patch-panel" aria-label="修改影响"><header><h3><GitBranch/>修改影响</h3>{patch&&<button className="icon-button" aria-label="关闭影响预览" onClick={onClose}><X/></button>}</header>{!patch?<><p className="empty-note">先修改正文，再检查它如何影响未来</p><div className="steps"><span><b>1</b>正文保存<small>保留每次修改</small></span><ArrowRight/><span><b>2</b>补丁审阅<small>检查影响范围</small></span><ArrowRight/><span><b>3</b>状态提交<small>用于后续创作</small></span></div></>:<><p className="patch-summary">{patch.summary}</p><div className="meta-row"><span>基准 v{patch.baseVersion}</span><span>正文 r{patch.revision}</span><span>{patch.scope==='story'?'全书设定':'当前章节'}</span></div>{patch.operations.map((op: PatchOperation & {description?: string; summary?: string; statement?: string; source?: SourceAnchor},i)=><div className="operation" key={i}><span className="op-number">{i+1}</span><div>{op.description||op.summary||operationLabels[op.op]||'更新故事状态'}{(op.statement||op.source?.quote)&&<p className="patch-quote">{op.statement||op.source?.quote}</p>}<details><summary>查看技术细节</summary><pre>{JSON.stringify(op,null,2)}</pre></details></div></div>)}{patch.operations.length===0&&<p className="success-note"><Check/>没有新增全局记忆或文风禁令</p>}{(validation?.errors||[]).map((e,i)=><p key={i} className="error"><AlertCircle/>{typeof e==='string'?e:errorMessage(e)||JSON.stringify(e)}</p>)}{(patch.questions||[]).map((q,i)=><p className="warning" key={i}>{q}</p>)}<div className="impact-rows">{(validation?.impacts||[]).map((p,i)=><div className="impact-row" key={p.id||i}><span className={'status '+(p.status==='invalid'?'amber':'')}>{p.status==='invalid'?'需重规划':'保留'}</span><span>{p.title||p.label||p.id}<small>{p.reason}</small></span></div>)}</div><button className="primary commit-button" disabled={!validation?.valid} onClick={onCommit}><Check/>确认并提交状态</button><small className="fine">保存正文与提交记忆是独立操作，提交前不会改变已确认事实</small></>}</section>}
