import {useState,useRef,useEffect} from 'react';
import {ArrowRight,Plus,X,Check,AlertCircle,Download,Layers,FileText} from 'lucide-react';
import * as engine from './domain/engine.js';
import {loadWorkspace,persistWorkspace,download} from './storage.js';
import Sidebar from './components/Sidebar.jsx';import Editor from './components/Editor.jsx';import Inspector from './components/Inspector.jsx';import PatchPanel from './components/PatchPanel.jsx';import DraftPanel from './components/DraftPanel.jsx';import HistoryView from './components/HistoryView.jsx';import ProjectWizard from './components/ProjectWizard.jsx';import {createTemplateAdapter} from './adapters/provider.js';import {createServerProvider} from './authoring/live-provider.js';import ProviderPanel from './components/ProviderPanel.jsx';
function initial(){try{return {workspace:loadWorkspace(),error:''}}catch(e){return {workspace:{format:1,serial:0,state:engine.createInitialState(),editing:{},patch:null},error:e.message}}}
export default function App(){const [{workspace:boot,error:bootError}]=useState(initial);const [workspace,setWorkspace]=useState(boot),ref=useRef(boot);const [tab,setTab]=useState('write'),[selected,setSelected]=useState('ch2'),[notice,setNotice]=useState(bootError),[error,setError]=useState(!!bootError),[evidence,setEvidence]=useState(null),[showContext,setShowContext]=useState(false),[wizard,setWizard]=useState(false),[classify,setClassify]=useState(false),[statement,setStatement]=useState(''),[busy,setBusy]=useState(false),[providerSettings,setProviderSettings]=useState(false),[interpretation,setInterpretation]=useState(null),[targetFact,setTargetFact]=useState('');const s=workspace.state,c=s.chapters.find(c=>c.id===selected)||s.chapters[0],value=workspace.editing[c.id]??c.text,dirty=value!==c.text,patch=workspace.patch,validation=patch?engine.validatePatch(s,patch):null,plans=engine.getImpacts(s),mode=workspace.providerMode||'template',provider=mode==='server'?createServerProvider():createTemplateAdapter();
 function notify(text,bad=false){setNotice(text);setError(bad)}
 function persist(next){try{const saved=persistWorkspace(next,ref.current.serial);ref.current=saved;setWorkspace(saved);return saved}catch(e){notify(e.message,true);return null}}
 function change(text){persist({...ref.current,editing:{...ref.current.editing,[c.id]:text}})}
 function mutate(fn,message){try{const next=fn(ref.current.state);if(persist({...ref.current,state:next})){notify(message);return next}}catch(e){notify(e.message,true)}}
 function analyze(){try{const old=ref.current,chapter=old.state.chapters.find(x=>x.id===c.id),text=old.editing[c.id]??chapter.text;const next=engine.saveRevision(old.state,c.id,text,chapter.revision),p=engine.proposePatch(next,c.id);if(persist({...old,state:next,editing:{...old.editing,[c.id]:undefined},patch:p}))notify(p.status==='blocked'?'正文已保存；这处修改需要语义澄清，记忆未改变':'正文已保存，请检查右侧修改影响',p.status==='blocked')}catch(e){notify(e.message,true)}}
 function commit(){const result=mutate(st=>engine.commitPatch(st,ref.current.patch),ref.current.state.mode==='custom'?'状态已提交；自建项目的通用语义依赖仍需作者复核':'状态已提交。相关计划已复核，其他计划保留');if(result)persist({...ref.current,patch:null})}
 async function generate(){if(Object.entries(ref.current.editing).some(([id,t])=>t!==undefined&&t!==s.chapters.find(c=>c.id===id)?.text)){notify('请先保存并分析正在编辑的正文，再生成下一场景',true);return}
 setBusy(true);try{let next;if(s.mode==='custom'||mode==='server'){const index=s.chapters.findIndex(ch=>ch.id===c.id);if(index>0&&s.chapters[index-1].status!=='ACCEPTED')throw Error('请先审阅并接受前一章，再继续下一章');const context=engine.getContext(s);const project=s.config||{projectId:s.projectId,title:s.title,idea:'林夏回到雾港，发现母亲持续收到神秘来信；陈默与死者的关系等待查证。',protagonist:'林夏',pov:'第三人称限知',tone:'克制而不安',goal:'查清母亲旧信与雾港命案的联系',boundaries:'不可让警方无来源提前获知秘密',outline:s.chapters.map(ch=>({id:ch.id,title:ch.title,goal:'沿已有线索推进，保持角色知识边界'}))};const output=await provider.generateChapter({project,chapterIndex:index,context});next=engine.stageProviderDraft(ref.current.state,{...output,context,staging:mode==='server'?output.staging:[]},c.id);if(persist({...ref.current,state:next}))notify(mode==='server'?'模型候选稿已返回；尚未进入已确认状态，请完成独立结构检查和模型审阅':'模板候选稿已生成，未写入正式记忆；真实模型尚未连接')}else next=mutate(engine.generateDraft,'候选稿已生成，尚未进入故事记忆');if(next)setTimeout(()=>document.getElementById('drafts')?.scrollIntoView({behavior:'smooth',block:'start'}),60)}catch(e){notify(e.message,true)}finally{setBusy(false)}}
 async function review(id){if(busy)return;const snapshot=ref.current.state,draft=snapshot.drafts.find(d=>d.id===id);const next=mutate(st=>engine.reviewDraft(st,id),'结构审查已完成');if(!next||!draft?.requiresSemanticReview)return;setBusy(true);try{const expected={stateVersion:next.version,draftRevision:draft.revision,textHash:engine.hash(draft.text)},report=await createServerProvider().reviewChapter({text:draft.text,chapterId:draft.chapterId||'ch3',context:engine.getContext(next)});mutate(st=>engine.attachSemanticReview(st,id,report,expected),'模型审阅已返回，仅作为可追溯建议；不会自行修改故事状态')}catch(e){notify(e.message,true)}finally{setBusy(false)}}
 async function prepareAnalysis(){setTargetFact('');if(mode!=='server'){setStatement('');setInterpretation(null);setClassify(true);return}setBusy(true);setInterpretation(null);try{const old=ref.current,chapter=old.state.chapters.find(x=>x.id===c.id),beforeText=chapter.revisions.find(r=>r.revision===chapter.syncedRevision)?.text||chapter.text,next=engine.saveRevision(old.state,c.id,old.editing[c.id]??chapter.text,chapter.revision);if(!persist({...old,state:next,editing:{...old.editing,[c.id]:undefined}}))return;const ctx=engine.getContext(next),after=next.chapters.find(x=>x.id===c.id),report=await provider.interpretRevision({beforeText,afterText:after.text,chapterId:c.id,context:ctx});const latest=ref.current.state.chapters.find(x=>x.id===c.id);if(ref.current.state.version!==next.version||latest.revision!==after.revision)throw Error('分析返回时正文或状态已变化，请重新分析');setInterpretation(report);setStatement('');setClassify(true);notify('模型仅提出改文解释，需由你确认后才能准备补丁')}catch(e){notify(e.message,true)}finally{setBusy(false)}}
 function createProject(config){const chapters=config.outline.map((p,i)=>({title:`第${['一','二','三'][i]}章 ${p.title}`}));const next=engine.createProjectFromConfig({...config,chapters});const archived=[...(ref.current.archived||[]),{state:ref.current.state,editing:ref.current.editing,patch:ref.current.patch}];if(!persist({...ref.current,state:next,editing:{},patch:null,archived}))throw Error('项目保存失败，请先导出原项目');setSelected('ch1');setTab('write');setWizard(false);notify('故事约定与前三章计划已保存，点击生成当前章开始创作')}
 function switchProject(id){const old=ref.current,list=old.archived||[],target=list.find(p=>p.state.projectId===id);if(!target)return;persist({...old,...target,archived:[...list.filter(p=>p.state.projectId!==id),{state:old.state,editing:old.editing,patch:old.patch}]});setSelected('ch1');setTab('write');notify('已切换项目，原项目及其编辑已保留')}
 function authorClassify(intent){try{const old=ref.current,chapter=old.state.chapters.find(x=>x.id===c.id),next=engine.saveRevision(old.state,c.id,old.editing[c.id]??chapter.text,chapter.revision),p=engine.proposeCustomPatch(next,c.id,{intent,statement,...(targetFact?{targetFactId:targetFact}:{})});if(persist({...old,state:next,editing:{...old.editing,[c.id]:undefined},patch:p})){setClassify(false);notify('已按你的明确分类准备补丁，请审阅后提交')}}catch(e){notify(e.message,true)}}

 useEffect(()=>{function changed(e){if(e.key==='nexusscribe.demo.v1')notify('另一窗口已更新项目，请刷新后继续，避免覆盖新内容',true)}window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed)},[]);
 return <div className="app-shell"><Sidebar state={s} mode={mode} tab={tab} setTab={setTab} selected={selected} onSelect={id=>{setSelected(id);setTab('write')}} onExport={()=>download('NexusScribe-项目备份.json',workspace)} projects={workspace.archived||[]} onSwitch={switchProject}/><main className="workspace"><header className="topbar"><div><h1>{tab==='write'?c.title:tab==='memory'?'故事记忆':'版本记录'}</h1><p><span className={'save-dot '+(dirty?'pending':'')}/>{dirty?'编辑内容已暂存 · 等待分析':`已保存 · 正文 r${c.revision}`}<span className="separator">/</span>故事状态 v{s.version}</p></div><div className="top-actions"><button aria-label="模型运行方式" onClick={()=>setProviderSettings(true)}>模型</button><button onClick={()=>setWizard(true)}><Plus/>新建故事</button><button className="primary" disabled={busy} onClick={generate}>{busy?'正在生成…':s.mode==='custom'?'生成当前章':'生成下一场景'}<ArrowRight/></button></div></header>{notice&&<div className={'notice '+(error?'error':'')} role="status">{error?<AlertCircle/>:<Check/>}<span>{notice}</span><button className="icon-button" aria-label="关闭通知" onClick={()=>setNotice('')}><X/></button></div>}
 {tab==='write'?<>{s.mode==='custom'&&<div className="workflow-banner"><strong>已确认故事约定 → 三章规划 → 生成候选 → 审阅定稿 → 继续下一章</strong><br/>{s.config?.idea}<br/>当前章节状态：{c.status==='ACCEPTED'?'已接受':c.status==='PLANNED'?'待创作':c.status} · {mode==='server'?'使用真实服务端模型，候选结果仍需作者确认':'模板运行，真实模型待接入'}</div>}<Editor chapter={c} value={value} dirty={dirty} onChange={change} onAnalyze={s.mode==='custom'?prepareAnalysis:analyze} onPreset={()=>{change(value.replace(engine.NEVER_MET,engine.HAS_MET));notify('已插入预置设定修改，点击“保存并分析”查看影响')}} onPolish={()=>{change(value.replace('缓缓走向窗前','走到窗前').replace('雨点敲打着审讯室的窗','雨敲着审讯室的窗'));notify('已应用预置局部润色，不会推导全书文风偏好')}}/><div className="under-editor"><button className="text-button" onClick={()=>setShowContext(true)}><Layers/>查看场景上下文</button><button className="text-button" onClick={()=>download(s.title+'.txt',s.chapters.map(c=>c.title+'\n\n'+c.text).join('\n\n'),'text/plain')}><Download/>导出正文</button><span>{mode==='server'?'真实模型 · 结果必须验证与确认':s.mode==='custom'?'模板模式 · 作者确认改文类型 · 未连接真实模型':'演示解释器仅识别预置修改，其他改文保留待决'}</span></div><div id="drafts"><DraftPanel drafts={s.drafts} onEdit={(id,text)=>mutate(st=>engine.editDraft(st,id,text),'草稿编辑已保存；旧审查已失效，请重新审查')} onReview={review} onAccept={id=>mutate(st=>engine.acceptDraft(st,id),'已接受当前章，暂存事件已提交；可以继续下一章')} onReject={id=>mutate(st=>engine.rejectDraft(st,id),'已拒绝候选稿，暂存事件已隔离，不会进入故事记忆')}/></div></>:tab==='history'?<HistoryView state={s} onUndo={id=>mutate(st=>engine.undoCommit(st,id),'已创建补偿版本；原正文保留，请复核正文与设定的一致性')}/>:<section className="full-view"><h2>让每条记忆都有来处</h2><p className="muted">世界事实、角色认知、未来计划与候选状态分别管理</p><div className="memory-sections">{[['已确认事实',s.facts],['角色认知',s.knowledge],['支持证据',s.evidence],['已接受事件',s.events],['读者披露',s.disclosures]].map(([title,items])=><section key={title}><h3>{title}<span>{items.length}</span></h3>{items.length?items.map((x,i)=><button className="memory-record" key={x.id||i} onClick={()=>setEvidence(x)}><FileText/><span>{x.label||x.proposition||x.quote||x.id}<small>{x.status|| (x.active?'有效':'失效')}</small></span><ArrowRight/></button>):<p className="fine">暂无记录，未接受的候选事件不会出现在这里</p>}</section>)}</div></section>}
 </main><Inspector state={s} plans={plans} onEvidence={setEvidence}><PatchPanel patch={patch} validation={validation} onCommit={commit} onClose={()=>persist({...ref.current,patch:null})}/></Inspector>
 {(evidence||showContext)&&<div className="modal-backdrop" onClick={()=>{setEvidence(null);setShowContext(false)}}><section className="modal" role="dialog" aria-modal="true" aria-label={evidence?'来源证据':'场景上下文'} onClick={e=>e.stopPropagation()}><header><h2>{evidence?'来源与版本':'场景上下文包'}</h2><button className="icon-button" aria-label="关闭详情" onClick={()=>{setEvidence(null);setShowContext(false)}}><X/></button></header><p className="muted">原始证据保留指定 revision。结构化状态不会替代原文。</p><pre>{JSON.stringify(evidence||engine.getContext(s),null,2)}</pre></section></div>}
 {wizard&&<ProjectWizard provider={provider} onCreate={createProject} onCancel={()=>setWizard(false)}/>}
 {providerSettings&&<ProviderPanel mode={mode} onMode={newMode=>{if(persist({...ref.current,providerMode:newMode})){setProviderSettings(false);notify(newMode==='server'?'已选择服务端模型；每次调用受服务端上限控制，失败不会回退模板':'已选择离线模板，不调用外部模型')}}} onClose={()=>setProviderSettings(false)}/>}
 {classify&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="确认改文类型"><header><h2>这次修改如何影响故事？</h2><button aria-label="关闭分类" className="icon-button" onClick={()=>setClassify(false)}><X/></button></header><p className="muted">{interpretation?'模型解释是候选建议。请检查下列证据，再明确选择局部表达或确认一条正文设定。':'当前未连接语义模型。请明确选择只保存局部表达，或从正文中摘取一条已确认的设定。'}</p>{interpretation&&<div className="model-review"><h4>模型解释</h4><p>{interpretation.summary}</p>{interpretation.questions?.map((q,i)=><p key={i} className="warning">{q}</p>)}{interpretation.suggestedFacts?.map((f,i)=><button key={i} className="suggested-fact" onClick={()=>setStatement(f.sourceQuote)}>{f.label}<br/>原文：{f.sourceQuote}</button>)}<p className="model-limit">点击候选仅填入待确认内容，不会提交记忆</p></div>}<label className="form-label">设定操作<select aria-label="要替代的现有设定" value={targetFact} onChange={e=>setTargetFact(e.target.value)}><option value="">新增一条设定</option>{s.facts.filter(f=>f.status==='confirmed').map(f=><option value={f.id} key={f.id}>替代：{f.label}</option>)}</select></label><label className="form-label">确认的设定（须为正文精确片段）<textarea value={statement} onChange={e=>setStatement(e.target.value)} rows={3}/></label><div className="draft-actions"><button onClick={()=>authorClassify('local_prose')}>仅局部表达，不更新设定</button><button className="primary" disabled={!statement.trim()} onClick={()=>authorClassify('author_fact')}>按这条设定准备补丁</button></div></section></div>}

 </div>
}
